"""regession tests for the pluging IFC Check"""
# TODO check needed imports (intialy copied from regression/test_teaser.py)
import logging
import re
import shutil
import unittest
# import filecmp  # compare files, maybe not needed TODO delete ?
from lxml import html
from pathlib import Path

import buildingspy.development.regressiontest as u

import bim2sim
from bim2sim.kernel.decision.decisionhandler import DebugDecisionHandler
from bim2sim.utilities.test import RegressionTestBase
from bim2sim.utilities.types import IFCDomain, ZoningCriteria
from bim2sim.plugins.PluginIFCCheck.bim2sim_ifccheck import PluginIFCCheck

logger = logging.getLogger(__name__)


class RegressionTestIFCCheck(RegressionTestBase):
    """Class to setup up nad run regression test of PluginIFCCheck"""
    def setUp(self):
        self.results_src_dir = None
        self.results_dst_dir = None
        super().setUp()

    def tearDown(self):
        super().tearDown()

    @staticmethod
    def get_elements_html_file(filepath, xpaths):
        """Get specific elements for a html file.

        Args:
            filepath: path to a html file
            xpaths: list of xpaths (strings), like '//div[@class="fail percent"]'
        Returns:
            results: list of the specific elements
        """
        doc = html.fromstring(open(filepath).read())
        results = []
        for xpath in xpaths:
            elem = doc.xpath(xpath)
            elem_str = elem[0].text_content().strip()
            results.append(elem_str)
        return results

    def create_regression_setup(self):
        """
        Create a regression test setup based on BuildingsPy regression tests.

        This method uses the BuildingsPy library to create a regression test for
        the currents project TEASER modelica simulation model export.

        Args:
            tolerance: the tolerance in which the regression results will be
                accepted as valid
            batch_mode: in batch mode no input is required and no new results
                can be created

        """
        passed_regression_test = False
        return passed_regression_test

    def run_regression_test(self):
        """Run the regression test."""

        # html elements from test resources
        result_res = self.get_elements_html_file(
            self.path_result_file_ifc_tester_res,
            self.xpaths)
        # html elements from generated reports (while test run)
        result_test = self.get_elements_html_file(
            self.path_result_file_ifc_tester,
            self.xpaths)
        reg_test_res = (result_res == result_test)

        return [reg_test_res, result_res, result_test]

    def create_regression_results(self):
        """Creates regression results based on simulation model.

        If simulation is successful and regression results differ from
        new simulation results, the user is asked if the results should be
        overwritten.
        If simulation  is successful and simulation results are same with
        regression results nothing happens.
        If simulation is not successful nothing happens.
        """
        # TODO put something in
        pass

class TestRegressionIFCCheck(RegressionTestIFCCheck, unittest.TestCase):
    def test_run_ifc_check_fzk_haus_ids(self):
        """Run IFCCheck regression test with AC20-FZK-Haus.ifc
           checking the html report generated by IfcTester
        """

        ifc_names = {IFCDomain.arch: 'AC20-FZK-Haus.ifc'}
        project = self.create_project(ifc_names, PluginIFCCheck)

        
        # assign an IDS file, which is needed to check the ifc file by ifctester
        project.sim_settings.ids_file_path = (
                Path(bim2sim.__file__).parent /
                'plugins/PluginIFCCheck/bim2sim_ifccheck/ifc_bps.ids'
        )

        answers = ()
        handler = DebugDecisionHandler(answers)

        handler.handle(project.run())

        # paths result file ifc tester (ids)
        self.path_result_file_ifc_tester = self.project.paths.log / "ifc_ids_check.html"
        self.path_result_file_ifc_tester_res = "/home/cudok/Documents/12_ifc_check_ids/regression_stuff/ifc_ids_check.html"

        # xpaths to elements in html
        # fail percent (unique)
        xpath_fail_perc = '//div[@class="fail percent"]'
        # Specifications passed
        xpath_spec_pass = (
          '//p/span[@class="item" and ' +
          'contains(normalize-space(.),"Specifications passed")]/ strong[1]'
        )
        # Specifications total
        xpath_spec_total = (
          '//p/span[@class="item" ' +
          'and contains(normalize-space(.),"Specifications passed")]/ strong[2]'
        )
        # Requirements passed
        xpath_req_pass = (
            '//p/span[@class="item" and ' +
            'contains(normalize-space(.),"Requirements passed")]/ strong[1]'
        )
        # Requirements total
        xpath_req_total = (
            '//p/span[@class="item" and ' +
            'contains(normalize-space(.),"Requirements passed")]/ strong[2]'
        )
        # Checks passed
        xpath_checks_pass = (
            '//p/span[@class="item" and ' +
            'contains(normalize-space(.),"Checks passed")]/ strong[1]'
        )
        # Checks total
        xpath_checks_total = (
          '//p/span[@class="item" and ' +
          'contains(normalize-space(.),"Checks passed")]/ strong[2]'
        )

        self.xpaths = [
            xpath_fail_perc,
            xpath_spec_pass, xpath_spec_total,
            xpath_req_pass, xpath_req_total,
            xpath_checks_pass, xpath_checks_total]

        reg_result = self.run_regression_test()

        self.assertTrue(reg_result[0], "Comparison of the ifc tester " +
                        "html reports (IDS) fails. " +
                        "expected: {} ".format(reg_result[1]) +
                        "test: {}".format(reg_result[2]))

    def test_run_ifc_check_fzk_haus_sum_prop(self):
        """Run IFCCheck regression test with AC20-FZK-Haus.ifc
           checking the html report "summary_prob" generated
           by bim2sim specific checks.
        """

        ifc_names = {IFCDomain.arch: 'AC20-FZK-Haus.ifc'}
        project = self.create_project(ifc_names, PluginIFCCheck)

        # assign an IDS file, which is needed to check the ifc file
        # by ifctester
        project.sim_settings.ids_file_path = (
                Path(bim2sim.__file__).parent /
                'plugins/PluginIFCCheck/bim2sim_ifccheck/ifc_bps.ids'
        )

        answers = ()
        handler = DebugDecisionHandler(answers)

        handler.handle(project.run())

        # paths result file ifc tester (ids)
        self.path_result_file_ifc_tester = self.project.paths.log / "ARCH_AC20-FZK-Haus_error_summary_prop.html"
        self.path_result_file_ifc_tester_res = "/home/cudok/Documents/12_ifc_check_ids/regression_stuff/ARCH_AC20-FZK-Haus_error_summary_prop.html"

        # xpaths to elements in html
        # Total IFCProduct with missing properties
        xpath_prod_with_miss_prop_total = (
            '//tr[td[@class="tg-fymr" and ' +
            'normalize-space(.)="Total IFCProduct with missing properties:"]]' +
            '/td[@class="tg-dvpl"][normalize-space()]'
                   )
        # Total missing properties in IFCProducts:
        xpath_miss_prop_in_prod_total = (
            '//tr[td[@class="tg-fymr" and ' +
            'normalize-space(.)="Total missing properties in IFCProducts:"]]' +
            '/td[@class="tg-dvpl"][normalize-space()]'
                   )
        self.xpaths = [
                  xpath_prod_with_miss_prop_total,
                  xpath_miss_prop_in_prod_total,

                       ]

        reg_result = self.run_regression_test()

        self.assertTrue(reg_result[0], "Comparison of the 'summary prop' " +
                        "html reports (bim2sim specific check) fails. " +
                        "expected: {} ".format(reg_result[1]) +
                        "test: {}".format(reg_result[2]))

    def test_run_ifc_check_fzk_haus_sum_inst(self):
        """Run IFCCheck regression test with AC20-FZK-Haus.ifc
           checking the html report "summary_inst" generated
           by bim2sim specific checks.
        """

        ifc_names = {IFCDomain.arch: 'AC20-FZK-Haus.ifc'}
        project = self.create_project(ifc_names, PluginIFCCheck)

        # assign an IDS file, which is needed to check the ifc file
        # by ifctester
        project.sim_settings.ids_file_path = (
                Path(bim2sim.__file__).parent /
                'plugins/PluginIFCCheck/bim2sim_ifccheck/ifc_bps.ids'
        )

        answers = ()
        handler = DebugDecisionHandler(answers)

        handler.handle(project.run())

        # paths result file ifc tester (ids)
        self.path_result_file_ifc_tester = self.project.paths.log / "ARCH_AC20-FZK-Haus_error_summary_inst.html"
        self.path_result_file_ifc_tester_res = "/home/cudok/Documents/12_ifc_check_ids/regression_stuff/ARCH_AC20-FZK-Haus_error_summary_inst.html"

        # xpaths to elements in html
        # Total IFCProduct with errors
        xpath_prod_with_errors_total = (
            '//tr[td[@class="tg-fymr" and ' +
            'normalize-space(.)="Total IFCProduct with errors:"]]' +
            '/td[@class="tg-dvpl"][normalize-space()]'
                   )
        # Total errors in IFCProducts:
        xpath_errors_in_prod_total = (
            '//tr[td[@class="tg-fymr" and ' +
            'normalize-space(.)="Total errors in IFCProducts:"]]' +
            '/td[@class="tg-dvpl"][normalize-space()]'
                   )

        # Total IfcRelSpaceBoundary with errors:
        xpath_errors_in_sb_total = (
            '//tr[td[@class="tg-fymr" and ' +
            'normalize-space(.)="Total IfcRelSpaceBoundary with errors:"]]' +
            '/td[@class="tg-dvpl"][normalize-space()]'
                   )

        # Total errors in IfcRelSpaceBoundary:
        xpath_errors_in_relsb_total = (
            '//tr[td[@class="tg-fymr" and ' +
            'normalize-space(.)="Total errors in IfcRelSpaceBoundary:"]]' +
            '/td[@class="tg-dvpl"][normalize-space()]'
                   )
        self.xpaths = [
                  xpath_prod_with_errors_total,
                  xpath_errors_in_prod_total,
                  xpath_errors_in_sb_total,
                  xpath_errors_in_relsb_total,
                       ]

        reg_result = self.run_regression_test()

        self.assertTrue(reg_result[0], "Comparison of the 'summary inst' " +
                        "html reports (bim2sim specific check) fails. " +
                        "expected: {} ".format(reg_result[1]) +
                        "test: {}".format(reg_result[2]))
