"""regession tests for the pluging IFC Check"""
import logging
import unittest
from lxml import html
from pathlib import Path


import bim2sim
from bim2sim.kernel.decision.decisionhandler import DebugDecisionHandler
from bim2sim.utilities.test import RegressionTestBase
from bim2sim.utilities.types import IFCDomain
from bim2sim.plugins.PluginIFCCheck.bim2sim_ifccheck import PluginIFCCheck

logger = logging.getLogger(__name__)


class Gen_xpath:
    """for genaration of xpaths."""

    def __init__(self, xpath_incl_var):
        """Initiate Gen_xpath class.

        Args:
          xpaht_incl_var: xpaht including placeholder (here '{}')
        """
        self.xpath_incl_var = xpath_incl_var

    def gen_xpath_name_pos(self, name_ele: str, pos_ele: int) -> str:
        """Generate a xpart in html report for checks.

        Args:
          name_ele: name of the element
          pos_ele: number of the item in the element
        Retruns:
          xpath: str
                 example = ('//p/span[@class="item" and ' +
                           'contains(normalize-space(.),"{}")]/ strong[{}]')
        """
        xpath = self.xpath_incl_var.format(name_ele, pos_ele)
        return xpath

    def gen_xpath_name(self, name_ele: str) -> str:
        """Generate a xpart in html report for checks.

        Args:
          name_ele: name of the element
        Retruns:
          xpath: str
                 example = ('//p/span[@class="item" and ' +
                           'contains(normalize-space(.),"{}")]/')
        """
        xpath = self.xpath_incl_var.format(name_ele)
        return xpath

class RegressionTestIFCCheck(RegressionTestBase):
    """Class to setup up nad run regression test of PluginIFCCheck"""
    def setUp(self):
        self.results_src_dir = None
        self.results_dst_dir = None
        super().setUp()

    def tearDown(self):
        super().tearDown()

    @staticmethod
    def get_elements_html_file(filepath, xpaths):
        """Get specific elements for a html file.

        Args:
            filepath: path to a html file
            xpaths: list of xpaths (strings),
                    like '//div[@class="fail percent"]'
        Returns:
            results: list of the specific elements
        """
        with open(filepath, 'r') as f:
            html_code = f.read()
        doc = html.fromstring(html_code)
        results = []
        for xpath in xpaths:
            elem = doc.xpath(xpath)
            elem_str = elem[0].text_content().strip()
            results.append(elem_str)
        return results

    def run_regression_test(self):
        """Run the regression test."""

        # html elements from test resources
        result_res = self.get_elements_html_file(
            self.path_result_file_ifc_tester_res,
            self.xpaths)
        # html elements from generated reports (while test run)
        result_test = self.get_elements_html_file(
            self.path_result_file_ifc_tester,
            self.xpaths)
        reg_test_res = (result_res == result_test)

        return [reg_test_res, result_res, result_test]


class TestRegressionIFCCheck(RegressionTestIFCCheck, unittest.TestCase):
    def test_run_ifc_check_fzk_haus_ids(self):
        """Run IFCCheck regression test with AC20-FZK-Haus.ifc
           checking the html report generated by IfcTester
        """

        ifc_names = {IFCDomain.arch: 'AC20-FZK-Haus.ifc'}
        project = self.create_project(ifc_names, PluginIFCCheck)

        # assign an IDS file, which is needed to check the ifc file by ifctester
        project.sim_settings.ids_file_path = (
                Path(bim2sim.__file__).parent /
                'plugins/PluginIFCCheck/bim2sim_ifccheck/ifc_bps.ids'
        )

        answers = ()
        handler = DebugDecisionHandler(answers)

        handler.handle(project.run())

        # paths result file ifc tester (ids)
        self.path_result_file_ifc_tester = (
            self.project.paths.log / "ifc_ids_check.html"
        )
        self.path_result_file_ifc_tester_res = (
            Path(bim2sim.__file__).parent.parent /
            'test/resources/ifc_check/regression_results/ifc_ids_check.html'
        )

        # xpaths to elements in html
        # fail percent (unique)
        xpath_fail_perc = '//div[@class="fail percent"]'
        # create function for xpath generation
        xpath_ids_var = Gen_xpath(
                xpath_incl_var = ('//p/span[@class="item" and ' +
                                  'contains(normalize-space(.),"{}")]/ strong[{}]'))

        # Specifications passed
        xpath_spec_pass = xpath_ids_var.gen_xpath_name_pos("Specifications passed", 1)
        # Specifications total
        xpath_spec_total = xpath_ids_var.gen_xpath_name_pos("Specifications passed", 2)
        # Requirements passed
        xpath_req_pass = xpath_ids_var.gen_xpath_name_pos("Requirements passed", 1)
        # Requirements total
        xpath_req_total = xpath_ids_var.gen_xpath_name_pos("Requirements passed", 2)
        # Checks passed
        xpath_checks_pass = xpath_ids_var.gen_xpath_name_pos("Checks passed", 1)
        # Checks total
        xpath_checks_total = xpath_ids_var.gen_xpath_name_pos("Checks passed", 2)

        self.xpaths = [
            xpath_fail_perc,
            xpath_spec_pass, xpath_spec_total,
            xpath_req_pass, xpath_req_total,
            xpath_checks_pass, xpath_checks_total]

        reg_result = self.run_regression_test()

        self.assertTrue(reg_result[0], "Comparison of the ifc tester " +
                        "html reports (IDS) fails. " +
                        "expected: {} ".format(reg_result[1]) +
                        "test: {}".format(reg_result[2]))

    def test_run_ifc_check_fzk_haus_sum_prop(self):
        """Run IFCCheck regression test with AC20-FZK-Haus.ifc
           checking the html report "summary_prop" generated
           by bim2sim specific checks.
        """

        ifc_names = {IFCDomain.arch: 'AC20-FZK-Haus.ifc'}
        project = self.create_project(ifc_names, PluginIFCCheck)

        # assign an IDS file, which is needed to check the ifc file
        # by ifctester
        project.sim_settings.ids_file_path = (
                Path(bim2sim.__file__).parent /
                'plugins/PluginIFCCheck/bim2sim_ifccheck/ifc_bps.ids'
        )

        answers = ()
        handler = DebugDecisionHandler(answers)

        handler.handle(project.run())

        # paths result file ifc tester (ids)
        self.path_result_file_ifc_tester = (
            self.project.paths.log /
            "ARCH_AC20-FZK-Haus_error_summary_prop.html"
        )
        self.path_result_file_ifc_tester_res = (
            Path(bim2sim.__file__).parent.parent /
            'test/resources/ifc_check/regression_results/' /
            'ARCH_AC20-FZK-Haus_error_summary_prop.html'
        )

        # xpaths to elements in html
        # create function for xpath generation
        xpath_prop_var = Gen_xpath(
                xpath_incl_var = (
            '//tr[td[@class="tg-fymr" and ' +
            'normalize-space(.)="{}"]]' +
            '/td[@class="tg-dvpl"][normalize-space()]'))

        # Total IFCProduct with missing properties
        xpath_prod_with_miss_prop_total = xpath_prop_var.gen_xpath_name(
            "Total IFCProduct with missing properties:")
        # Total missing properties in IFCProducts:
        xpath_miss_prop_in_prod_total = xpath_prop_var.gen_xpath_name(
            "Total missing properties in IFCProducts:")

        self.xpaths = [
                  xpath_prod_with_miss_prop_total,
                  xpath_miss_prop_in_prod_total,

                       ]

        reg_result = self.run_regression_test()

        self.assertTrue(reg_result[0], "Comparison of the 'summary prop' " +
                        "html reports (bim2sim specific check) fails. " +
                        "expected: {} ".format(reg_result[1]) +
                        "test: {}".format(reg_result[2]))

    def test_run_ifc_check_fzk_haus_sum_inst(self):
        """Run IFCCheck regression test with AC20-FZK-Haus.ifc
           checking the html report "summary_inst" generated
           by bim2sim specific checks.
        """

        ifc_names = {IFCDomain.arch: 'AC20-FZK-Haus.ifc'}
        project = self.create_project(ifc_names, PluginIFCCheck)

        # assign an IDS file, which is needed to check the ifc file
        # by ifctester
        project.sim_settings.ids_file_path = (
                Path(bim2sim.__file__).parent /
                'plugins/PluginIFCCheck/bim2sim_ifccheck/ifc_bps.ids'
        )

        answers = ()
        handler = DebugDecisionHandler(answers)

        handler.handle(project.run())

        # paths result file ifc tester (ids)
        self.path_result_file_ifc_tester = (
            self.project.paths.log /
            "ARCH_AC20-FZK-Haus_error_summary_inst.html"
        )
        self.path_result_file_ifc_tester_res = (
            Path(bim2sim.__file__).parent.parent /
            'test/resources/ifc_check/regression_results/' /
            'ARCH_AC20-FZK-Haus_error_summary_inst.html'
        )

        # xpaths to elements in html
        # Total IFCProduct with errors
        xpath_prod_with_errors_total = (
            '//tr[td[@class="tg-fymr" and ' +
            'normalize-space(.)="Total IFCProduct with errors:"]]' +
            '/td[@class="tg-dvpl"][normalize-space()]'
                   )
        # Total errors in IFCProducts:
        xpath_errors_in_prod_total = (
            '//tr[td[@class="tg-fymr" and ' +
            'normalize-space(.)="Total errors in IFCProducts:"]]' +
            '/td[@class="tg-dvpl"][normalize-space()]'
                   )

        # Total IfcRelSpaceBoundary with errors:
        xpath_errors_in_sb_total = (
            '//tr[td[@class="tg-fymr" and ' +
            'normalize-space(.)="Total IfcRelSpaceBoundary with errors:"]]' +
            '/td[@class="tg-dvpl"][normalize-space()]'
                   )

        # Total errors in IfcRelSpaceBoundary:
        xpath_errors_in_relsb_total = (
            '//tr[td[@class="tg-fymr" and ' +
            'normalize-space(.)="Total errors in IfcRelSpaceBoundary:"]]' +
            '/td[@class="tg-dvpl"][normalize-space()]'
                   )
        self.xpaths = [
                  xpath_prod_with_errors_total,
                  xpath_errors_in_prod_total,
                  xpath_errors_in_sb_total,
                  xpath_errors_in_relsb_total,
                       ]

        reg_result = self.run_regression_test()

        self.assertTrue(reg_result[0], "Comparison of the 'summary inst' " +
                        "html reports (bim2sim specific check) fails. " +
                        "expected: {} ".format(reg_result[1]) +
                        "test: {}".format(reg_result[2]))

    def test_run_ifc_check_fzk_haus_sum(self):
        """Run IFCCheck regression test with AC20-FZK-Haus.ifc
           checking the html report "summary" generated
           by bim2sim specific checks.
        """

        ifc_names = {IFCDomain.arch: 'AC20-FZK-Haus.ifc'}
        project = self.create_project(ifc_names, PluginIFCCheck)

        # assign an IDS file, which is needed to check the ifc file
        # by ifctester
        project.sim_settings.ids_file_path = (
                Path(bim2sim.__file__).parent /
                'plugins/PluginIFCCheck/bim2sim_ifccheck/ifc_bps.ids'
        )

        answers = ()
        handler = DebugDecisionHandler(answers)

        handler.handle(project.run())

        # paths result file ifc tester (ids)
        self.path_result_file_ifc_tester = (
            self.project.paths.log /
            "ARCH_AC20-FZK-Haus_error_summary.html"
        )
        self.path_result_file_ifc_tester_res = (
            Path(bim2sim.__file__).parent.parent /
            'test/resources/ifc_check/regression_results/' /
            'ARCH_AC20-FZK-Haus_error_summary.html'
        )

        # xpaths to elements in html
        # IFC Version:
        xpath_ifc_version = (
            '//tr[td[@class="tg-dvpl" and ' +
            'normalize-space(.)="IFC Version:"]]' +
            '/td[@class="tg-dvpl"][2]'
                   )
        # Version error:
        xpath_ifc_version_error = (
            '//tr[td[@class="tg-dvpl" and ' +
            'normalize-space(.)="Version error:"]]' +
            '/td[@class="tg-dvpl"][2]'
                   )
        # Unique GUID:
        xpath_unique_guid = (
            '//tr[td[@class="tg-dvpl" and ' +
            'normalize-space(.)="Unique GUID:"]]' +
            '/td[@class="tg-dvpl"][2]'
                   )
        # Total non-unique GUIDs:
        xpath_nonunique_guid_total = (
            '//tr[td[@class="tg-dvpl" and ' +
            'normalize-space(.)="Total non-unique GUIDs:"]]' +
            '/td[@class="tg-dvpl"][2]'
                   )
        # Empty GUID:
        xpath_empty_guid = (
            '//tr[td[@class="tg-dvpl" and ' +
            'normalize-space(.)="Empty GUID:"]]' +
            '/td[@class="tg-dvpl"][2]'
                   )
        # Total Empty GUIDs:
        xpath_empty_guid_total = (
            '//tr[td[@class="tg-dvpl" and ' +
            'normalize-space(.)="Total Empty GUIDs:"]]' +
            '/td[@class="tg-dvpl"][2]'
                   )
        # Total IFCProduct with errors
        xpath_prod_with_errors_total = (
            '//tr[td[@class="tg-dvpl" and ' +
            'normalize-space(.)="Total IFCProduct with errors:"]]' +
            '/td[@class="tg-dvpl"][2]'
                   )
        self.xpaths = [
                xpath_ifc_version,
                xpath_ifc_version_error,
                xpath_unique_guid,
                xpath_nonunique_guid_total,
                xpath_empty_guid,
                xpath_empty_guid_total,
                xpath_prod_with_errors_total,
                       ]

        reg_result = self.run_regression_test()

        self.assertTrue(reg_result[0], "Comparison of the 'summary' " +
                        "html reports (bim2sim specific check) fails. " +
                        "expected: {} ".format(reg_result[1]) +
                        "test: {}".format(reg_result[2]))

    def test_run_ifc_check_fzk_haus_guid(self):
        """Run IFCCheck regression test with AC20-FZK-Haus.ifc
           checking the html report "summary_guid" generated
           by bim2sim specific checks.
        """

        ifc_names = {IFCDomain.arch: 'AC20-FZK-Haus.ifc'}
        project = self.create_project(ifc_names, PluginIFCCheck)

        # assign an IDS file, which is needed to check the ifc file
        # by ifctester
        project.sim_settings.ids_file_path = (
                Path(bim2sim.__file__).parent /
                'plugins/PluginIFCCheck/bim2sim_ifccheck/ifc_bps.ids'
        )

        answers = ()
        handler = DebugDecisionHandler(answers)

        handler.handle(project.run())

        # paths result file ifc tester (ids)
        self.path_result_file_ifc_tester = (
            self.project.paths.log /
            "ARCH_AC20-FZK-Haus_error_summary_guid.html"
        )
        self.path_result_file_ifc_tester_res = (
            Path(bim2sim.__file__).parent.parent /
            'test/resources/ifc_check/regression_results/' /
            'ARCH_AC20-FZK-Haus_error_summary_guid.html'
        )

        # xpaths to elements in html
        # Total non-unique GUIDs:
        xpath_nonunique_guid_total = (
            '//tr[td[@class="tg-fymr" and ' +
            'normalize-space(.)="Total non-unique GUIDs:"]]' +
            '/td[@class="tg-dvpl"][1]'
                   )
        # Total Empty GUIDs:
        xpath_empty_guid_total = (
            '//tr[td[@class="tg-fymr" and ' +
            'normalize-space(.)="Total Empty GUIDs:"]]' +
            '/td[@class="tg-dvpl"][1]'
                   )
        self.xpaths = [
                xpath_nonunique_guid_total,
                xpath_empty_guid_total,
                       ]

        reg_result = self.run_regression_test()

        self.assertTrue(reg_result[0], "Comparison of the 'summary_guid' " +
                        "html reports (bim2sim specific check) fails. " +
                        "expected: {} ".format(reg_result[1]) +
                        "test: {}".format(reg_result[2]))
