stages:
  - build-env

build_env:main:
 image: docker:latest
 stage: build-env
 services:
   - name: docker:18.09.7-dind
     command: ["--mtu=1440"]
 before_script:
   - docker login -u $CI_DEPLOY_TOKEN_USERNAME -p $CI_DEPLOY_TOKEN_PASSWORD $CI_REGISTRY_LOGIN
 script:
   - docker build -t $CI_REGISTRY/environment:master -f envBase.Dockerfile .
   - docker push $CI_REGISTRY/environment:master
 rules:
   - if: $CI_COMMIT_BRANCH == "main"
     changes:
        - envBase.Dockerfile
        - requirements.txt
     when: always
   - if: $CI_COMMIT_MESSAGE =~ /ci_build_env/
     when: manual



build_env:development:
 image: docker:latest
 stage: build-env
 services:
   - name: docker:18.09.7-dind
     command: ["--mtu=1440"]
 #- docker:18.09.7-dind
 before_script:
   - docker login -u $CI_DEPLOY_TOKEN_USERNAME -p $CI_DEPLOY_TOKEN_PASSWORD $CI_REGISTRY_LOGIN
 script:
   - docker build -t $CI_REGISTRY/environment:development -f envBase.Dockerfile .
 artifacts:
  expire_in: 1 hour
  paths:
    - $CI_REGISTRY/environment:development

 rules:
   - if: $CI_COMMIT_BRANCH == "development"
     changes:
        - envBase.Dockerfile
        - requirements.txt
        - .gitlab-ci.yml
     when: always
   - if: $CI_COMMIT_MESSAGE =~ /ci_build_env/
     when: manual


build_env:dymola:
 image: docker:latest
 stage: build-env
 services:
   - name: docker:18.09.7-dind
     command: ["--mtu=1440"]
 #- docker:18.09.7-dind
 before_script:
   - docker login -u $CI_DEPLOY_TOKEN_USERNAME_DYMOLA -p $CI_DEPLOY_TOKEN_PASSWORD_DYMOLA $CI_REGISTRY_LOGIN_DYMOLA   # login dymola docker reg
 script:
   - docker build -t $CI_REGISTRY/environment:dymola -f envBaseDymola.Dockerfile .
   - docker login -u $CI_DEPLOY_TOKEN_USERNAME -p $CI_DEPLOY_TOKEN_PASSWORD $CI_REGISTRY_LOGIN  # login bim2sim reg
   - docker push $CI_REGISTRY/environment:dymola
 rules:
   - if: $CI_COMMIT_BRANCH == "development"
     changes:
        - envBaseDymola.Dockerfile
        - requirements.txt
        - .gitlab-ci.yml
     when: always
   - if: $CI_COMMIT_MESSAGE =~ /ci_build_env/
     when: manual

