stages:
  - test

.test-default: &test-default
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"
      changes:
        - bim2sim/**/*.py
      when: always
    - if: $CI_COMMIT_MESSAGE =~ /ci_test/
      when: manual


test_Base:
  <<: *test-default
  image: $CI_REGISTRY/environment:development
  stage: test
  services:
   - name: docker:18.09.7-dind
     command: ["--mtu=1440"]
  before_script:
    - pip install coverage
    - pip install coverage-badge
  script:
    - mv ./* /bim2sim-coding/
    - cd /bim2sim-coding
    - wget --quiet -O /bim2sim-coding/test/TestModels/download.zip https://rwth-aachen.sciebo.de/s/R6K1H5Z9fiB3EoB/download
    - unzip /bim2sim-coding/test/TestModels/download.zip -d /bim2sim-coding/test/TestModels/
    - coverage run -m unittest discover /bim2sim-coding/test
    - coverage report -i
    - mkdir -p $CI_COMMIT_REF_NAME/coverage
    - coverage html -i
    - cp htmlcov/* $CI_COMMIT_REF_NAME/coverage/
    # skip this for now as its only cosmetic and leads to problems
    # - coverage-badge -o coverage.svg
    # - cp coverage.svg $CI_COMMIT_REF_NAME/coverage/
  artifacts:
    paths:
    - $CI_COMMIT_REF_NAME/coverage

test_EP:
  <<: *test-default
  image: $CI_REGISTRY/environment:energyplus
  stage: test
  services:
   - name: docker:18.09.7-dind
     command: ["--mtu=1440"]
  before_script:
    - pip install coverage
    - pip install coverage-badge
  script:
    - mv ./* /bim2sim-coding/
    - cd /bim2sim-coding
    - cat /bim2sim-coding/bim2sim/plugins/PluginEnergyPlus/data/Minimal.idf
    - wget --quiet -O /bim2sim-coding/test/TestModels/download.zip https://rwth-aachen.sciebo.de/s/SAUQQgvwqeS96ix/download
    - unzip /bim2sim-coding/test/TestModels/download.zip -d /bim2sim-coding/test/TestModels/
    - coverage run -m unittest discover /bim2sim-coding/bim2sim/plugins/PluginEnergyPlus/test/integration_test
    - coverage report -i
    - mkdir -p $CI_COMMIT_REF_NAME/coverage
    - coverage html -i
    - cp htmlcov/* $CI_COMMIT_REF_NAME/coverage/
    # skip this for now as its only cosmetic and leads to problems
    # - coverage-badge -o coverage.svg
    # - cp coverage.svg $CI_COMMIT_REF_NAME/coverage/
  artifacts:
    paths:
    - $CI_COMMIT_REF_NAME/coverage

test_EP_regression:
  <<: *test-default
  image: $CI_REGISTRY/environment:energyplus
  stage: test
  before_script:
    - pip install coverage
    - pip install coverage-badge
  script:
    - mv ./* /bim2sim-coding/
    - cd /bim2sim-coding
    - cat /bim2sim-coding/bim2sim/plugins/PluginEnergyPlus/data/Minimal.idf
    - wget --quiet -O /bim2sim-coding/test/TestModels/download.zip https://rwth-aachen.sciebo.de/s/SAUQQgvwqeS96ix/download
    - unzip /bim2sim-coding/test/TestModels/download.zip -d /bim2sim-coding/test/TestModels/
    - wget --quiet -O /bim2sim-coding/bim2sim/assets/download.zip https://rwth-aachen.sciebo.de/s/5EQqe5g8x0x4lae/download
    - unzip /bim2sim-coding/bim2sim/assets/download.zip -d /bim2sim-coding/bim2sim/assets/
    - coverage run -m unittest discover /bim2sim-coding/bim2sim/plugins/PluginEnergyPlus/test/regression_test
    - coverage report -i
    - mkdir -p $CI_COMMIT_REF_NAME/coverage
    - coverage html -i
    - cp htmlcov/* $CI_COMMIT_REF_NAME/coverage/
    # skip this for now as its only cosmetic and leads to problems
    # - coverage-badge -o coverage.svg
    # - cp coverage.svg $CI_COMMIT_REF_NAME/coverage/
  artifacts:
    paths:
    - $CI_COMMIT_REF_NAME/coverage

test_TEASER:
  <<: *test-default
  image: $CI_REGISTRY/environment:teaser
  stage: test
  services:
   - name: docker:18.09.7-dind
     command: ["--mtu=1440"]
  before_script:
    - pip install coverage
    - pip install coverage-badge
  script:
    - mv ./* /bim2sim-coding/
    - cd /bim2sim-coding
    - wget --quiet -O /bim2sim-coding/test/TestModels/download.zip https://rwth-aachen.sciebo.de/s/SAUQQgvwqeS96ix/download
    - unzip /bim2sim-coding/test/TestModels/download.zip -d /bim2sim-coding/test/TestModels/
    - coverage run -m unittest discover /bim2sim-coding/bim2sim/plugins/PluginTEASER/test/integration_test
    - coverage report -i
    - mkdir -p $CI_COMMIT_REF_NAME/coverage
    - coverage html -i
    - cp htmlcov/* $CI_COMMIT_REF_NAME/coverage/
    # skip this for now as its only cosmetic and leads to problems
    # - coverage-badge -o coverage.svg
    # - cp coverage.svg $CI_COMMIT_REF_NAME/coverage/
  artifacts:
    paths:
    - $CI_COMMIT_REF_NAME/coverage

test_TEASER_regression:
  <<: *test-default
  image: $CI_REGISTRY/environment:teaser-dymola
  stage: test
  before_script:
    - pip install coverage
    - pip install coverage-badge
    - apt-get install xvfb -y
  script:
    - mv ./* /bim2sim-coding/
    - cd /bim2sim-coding
    - wget --quiet -O /bim2sim-coding/test/TestModels/download.zip https://rwth-aachen.sciebo.de/s/SAUQQgvwqeS96ix/download
    - unzip /bim2sim-coding/test/TestModels/download.zip -d /bim2sim-coding/test/TestModels/
    - wget --quiet -O /bim2sim-coding/bim2sim/assets/download.zip https://rwth-aachen.sciebo.de/s/5EQqe5g8x0x4lae/download
    - unzip /bim2sim-coding/bim2sim/assets/download.zip -d /bim2sim-coding/bim2sim/assets/
    - xvfb-run -n 77 coverage run -m unittest discover /bim2sim-coding/bim2sim/plugins/PluginTEASER/test/regression_test
    - coverage report -i
    - mkdir -p $CI_COMMIT_REF_NAME/coverage
    - coverage html -i
    - cp htmlcov/* $CI_COMMIT_REF_NAME/coverage/
    # skip this for now as its only cosmetic and leads to problems
    # - coverage-badge -o coverage.svg
    # - cp coverage.svg $CI_COMMIT_REF_NAME/coverage/
  artifacts:
    paths:
    - $CI_COMMIT_REF_NAME/coverage

test_CFD:
  <<: *test-default
  image: $CI_REGISTRY/environment:cfd
  stage: test
  services:
   - name: docker:18.09.7-dind
     command: ["--mtu=1440"]
  before_script:
    - pip install coverage
    - pip install coverage-badge
  script:
    - mv ./* /bim2sim-coding/
    - cd /bim2sim-coding
    - wget --quiet -O /bim2sim-coding/test/TestModels/download.zip https://rwth-aachen.sciebo.de/s/SAUQQgvwqeS96ix/download
    - unzip /bim2sim-coding/test/TestModels/download.zip -d /bim2sim-coding/test/TestModels/
    - coverage run -m unittest discover /bim2sim-coding/bim2sim/plugins/PluginCFD/test/integration_test
    - coverage report -i
    - mkdir -p $CI_COMMIT_REF_NAME/coverage
    - coverage html -i
    - cp htmlcov/* $CI_COMMIT_REF_NAME/coverage/
    # skip this for now as its only cosmetic and leads to problems
    # - coverage-badge -o coverage.svg
    # - cp coverage.svg $CI_COMMIT_REF_NAME/coverage/
  artifacts:
    paths:
    - $CI_COMMIT_REF_NAME/coverage

test_AixLib:
  <<: *test-default
  image: $CI_REGISTRY/environment:aixlib
  stage: test
  services:
   - name: docker:18.09.7-dind
     command: ["--mtu=1440"]
  before_script:
    - pip install coverage
    - pip install coverage-badge
  script:
    - mv ./* /bim2sim-coding/
    - cd /bim2sim-coding
    - wget --quiet -O /bim2sim-coding/test/TestModels/download.zip https://rwth-aachen.sciebo.de/s/R6K1H5Z9fiB3EoB/download
    - unzip /bim2sim-coding/test/TestModels/download.zip -d /bim2sim-coding/test/TestModels/
    - coverage run -m unittest discover /bim2sim-coding/bim2sim/plugins/PluginAixLib/test/integration_test
    - coverage report -i
    - mkdir -p $CI_COMMIT_REF_NAME/coverage
    - coverage html -i
    - cp htmlcov/* $CI_COMMIT_REF_NAME/coverage/
    # skip this for now as its only cosmetic and leads to problems
    # - coverage-badge -o coverage.svg
    # - cp coverage.svg $CI_COMMIT_REF_NAME/coverage/
  artifacts:
    paths:
    - $CI_COMMIT_REF_NAME/coverage

test_LCA:
  <<: *test-default
  image: $CI_REGISTRY/environment:development
  stage: test
  before_script:
    - pip install coverage
    - pip install coverage-badge
  script:
    - mv ./* /bim2sim-coding/
    - cd /bim2sim-coding
    - wget --quiet -O /bim2sim-coding/test/TestModels/download.zip https://rwth-aachen.sciebo.de/s/SAUQQgvwqeS96ix/download
    - unzip /bim2sim-coding/test/TestModels/download.zip -d /bim2sim-coding/test/TestModels/
    - coverage run -m unittest discover /bim2sim-coding/bim2sim/plugins/PluginLCA/test/integration_test
    - coverage report -i
    - mkdir -p $CI_COMMIT_REF_NAME/coverage
    - coverage html -i
    - cp htmlcov/* $CI_COMMIT_REF_NAME/coverage/
    # skip this for now as its only cosmetic and leads to problems
    # - coverage-badge -o coverage.svg
    # - cp coverage.svg $CI_COMMIT_REF_NAME/coverage/
  artifacts:
    paths:
    - $CI_COMMIT_REF_NAME/coverage