{% set version = "0.1.dev0" %}

package:
  name: "bim2sim"
  version: {{ version }}
source:
  path: ./

build:

  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  host:
    - python
    - pip
    - setuptools
  RUN:
    - bim2sim
    - pythonocc-core=7.6.2
    - ifcopenshell



about:
  home: https://github.com/BIM2SIM/bim2sim
  license: ???
  license_familY: ???
  license_file: ???
  summary: "Create simulation models from IFC files"