{% set name = "decision" %}
{% set version = "0.3.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 346038b3fac278fe0ce60e8b8d52845f07a83990fdd134737e9c11658e1421aa

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - decision
    - decision.core

about:
  home: "https://github.com/lycantropos/decision/"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Decision making problems."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
