---
title: plugin CFD
---
flowchart TB
    
subgraph taskRunIFC2CFD["task RunIFC2CFD"]
 subgraph "" 

  tRunIFC2CFD["bim2sim > plugins > PluginCFD > 
bim2sim_cfd > task >  
 RunIFC2CFD"]
  extRunIFC2CFD("  # todo @ eric infos hier ausfüllen . " )
 end

stateRunIFC2CFD[("state
 (reads/touches)")]
    direction RL
end
    