---
title: plugin EnergyPlus
---
flowchart TB
    
subgraph taskLoadIFC["task LoadIFC"]
 subgraph "" 

  tLoadIFC["bim2sim > tasks > common >  
 LoadIFC"]
  extLoadIFC(" Load all IFC files from PROJECT. " )
 end

stateLoadIFC[("state
 (reads/touches)")]
    
tLoadIFC -- ifc_files --> stateLoadIFC

end
    
subgraph taskCheckIfc["task CheckIfc"]
 subgraph "" 

  tCheckIfc["bim2sim > tasks > common >  
 CheckIfc"]
  extCheckIfc("  Check an IFC file, for a number of conditions
(missing information, incorrect information, etc)
that could lead on future tasks to fatal errors. " )
 end

stateCheckIfc[("state
 (reads/touches)")]
    
stateCheckIfc -- ifc_files --> tCheckIfc
direction RL
end
    
subgraph taskCreateElementsOnIfcTypes["task CreateElementsOnIfcTypes"]
 subgraph "" 

  tCreateElementsOnIfcTypes["bim2sim > tasks > common >  
 CreateElementsOnIfcTypes"]
  extCreateElementsOnIfcTypes(" Create bim2sim elements based on information of
IFC types. " )
 end

stateCreateElementsOnIfcTypes[("state
 (reads/touches)")]
    
stateCreateElementsOnIfcTypes -- ifc_files --> tCreateElementsOnIfcTypes

tCreateElementsOnIfcTypes -- elements, _initial_elements, ifc_files --> stateCreateElementsOnIfcTypes

end
    
subgraph taskCreateSpaceBoundaries["task CreateSpaceBoundaries"]
 subgraph "" 

  tCreateSpaceBoundaries["bim2sim > tasks > bps >  
 CreateSpaceBoundaries"]
  extCreateSpaceBoundaries(" Create space boundary elements from ifc. " )
 end

stateCreateSpaceBoundaries[("state
 (reads/touches)")]
    
stateCreateSpaceBoundaries -- ifc_files, elements --> tCreateSpaceBoundaries
direction RL
end
    
subgraph taskAddSpaceBoundaries2B["task AddSpaceBoundaries2B"]
 subgraph "" 

  tAddSpaceBoundaries2B["bim2sim > tasks > bps >  
 AddSpaceBoundaries2B"]
  extAddSpaceBoundaries2B(" Fill gaps in set of space boundary per space with
2B space boundaries. " )
 end

stateAddSpaceBoundaries2B[("state
 (reads/touches)")]
    
stateAddSpaceBoundaries2B -- elements --> tAddSpaceBoundaries2B

tAddSpaceBoundaries2B -- elements --> stateAddSpaceBoundaries2B

end
    
subgraph taskCorrectSpaceBoundaries["task CorrectSpaceBoundaries"]
 subgraph "" 

  tCorrectSpaceBoundaries["bim2sim > tasks > bps >  
 CorrectSpaceBoundaries"]
  extCorrectSpaceBoundaries(" Advanced geometric preprocessing for Space
Boundaries. " )
 end

stateCorrectSpaceBoundaries[("state
 (reads/touches)")]
    
stateCorrectSpaceBoundaries -- elements --> tCorrectSpaceBoundaries
direction RL
end
    
subgraph taskCreateRelations["task CreateRelations"]
 subgraph "" 

  tCreateRelations["bim2sim > tasks > common >  
 CreateRelations"]
  extCreateRelations(" Relations of elements, run() method holds detailed
information. " )
 end

stateCreateRelations[("state
 (reads/touches)")]
    
stateCreateRelations -- elements --> tCreateRelations
direction RL
end
    
subgraph taskDisaggregationCreationAndTypeCheck["task DisaggregationCreationAndTypeCheck"]
 subgraph "" 

  tDisaggregationCreationAndTypeCheck["bim2sim > tasks > bps >  
 DisaggregationCreationAndTypeCheck"]
  extDisaggregationCreationAndTypeCheck(" Disaggregation of elements, run() method holds
detailed information. " )
 end

stateDisaggregationCreationAndTypeCheck[("state
 (reads/touches)")]
    
stateDisaggregationCreationAndTypeCheck -- elements --> tDisaggregationCreationAndTypeCheck
direction RL
end
    
subgraph taskEnrichMaterial["task EnrichMaterial"]
 subgraph "" 

  tEnrichMaterial["bim2sim > tasks > bps >  
 EnrichMaterial"]
  extEnrichMaterial(" Enriches material properties that were recognized
as invalid LOD. " )
 end

stateEnrichMaterial[("state
 (reads/touches)")]
    
stateEnrichMaterial -- elements --> tEnrichMaterial
direction RL
end
    
subgraph taskEnrichUseConditions["task EnrichUseConditions"]
 subgraph "" 

  tEnrichUseConditions["bim2sim > tasks > bps >  
 EnrichUseConditions"]
  extEnrichUseConditions(" Enriches Use Conditions of thermal zones based on
decisions and translation of zone names. " )
 end

stateEnrichUseConditions[("state
 (reads/touches)")]
    
stateEnrichUseConditions -- elements --> tEnrichUseConditions
direction RL
end
    
subgraph taskWeather["task Weather"]
 subgraph "" 

  tWeather["bim2sim > tasks > common >  
 Weather"]
  extWeather(" Task to get the weather file for later simulation. " )
 end

stateWeather[("state
 (reads/touches)")]
    
stateWeather -- elements --> tWeather

tWeather -- weather_file --> stateWeather

end
    
subgraph taskCreateIdf["task CreateIdf"]
 subgraph "" 

  tCreateIdf["bim2sim > plugins > PluginEnergyPlus > 
bim2sim_energyplus > task >  
 CreateIdf"]
  extCreateIdf(" Create an EnergyPlus Input file. " )
 end

stateCreateIdf[("state
 (reads/touches)")]
    
stateCreateIdf -- elements, weather_file --> tCreateIdf

tCreateIdf -- idf, sim_results_path --> stateCreateIdf

end
    
subgraph taskIdfPostprocessing["task IdfPostprocessing"]
 subgraph "" 

  tIdfPostprocessing["bim2sim > plugins > PluginEnergyPlus > 
bim2sim_energyplus > task >  
 IdfPostprocessing"]
  extIdfPostprocessing(" Idf Postprocessin task. " )
 end

stateIdfPostprocessing[("state
 (reads/touches)")]
    
stateIdfPostprocessing -- elements, idf, ifc_files, sim_results_path --> tIdfPostprocessing
direction RL
end
    
subgraph taskExportIdfForCfd["task ExportIdfForCfd"]
 subgraph "" 

  tExportIdfForCfd["bim2sim > plugins > PluginEnergyPlus > 
bim2sim_energyplus > task >  
 ExportIdfForCfd"]
  extExportIdfForCfd("  Export Idf shapes as . " )
 end

stateExportIdfForCfd[("state
 (reads/touches)")]
    
stateExportIdfForCfd -- elements, idf --> tExportIdfForCfd
direction RL
end
    
subgraph taskSerializeElements["task SerializeElements"]
 subgraph "" 

  tSerializeElements["bim2sim > tasks > common >  
 SerializeElements"]
  extSerializeElements(" Serialize element structure, run() method holds
detailed information. " )
 end

stateSerializeElements[("state
 (reads/touches)")]
    
stateSerializeElements -- elements --> tSerializeElements

tSerializeElements -- serialized_elements --> stateSerializeElements

end
    
subgraph taskRunEnergyPlusSimulation["task RunEnergyPlusSimulation"]
 subgraph "" 

  tRunEnergyPlusSimulation["bim2sim > plugins > PluginEnergyPlus > 
bim2sim_energyplus > task >  
 RunEnergyPlusSimulation"]
  extRunEnergyPlusSimulation(" Run EnergyPlus simulation. " )
 end

stateRunEnergyPlusSimulation[("state
 (reads/touches)")]
    
stateRunEnergyPlusSimulation -- idf, sim_results_path --> tRunEnergyPlusSimulation
direction RL
end
    
subgraph taskCreateResultDF["task CreateResultDF"]
 subgraph "" 

  tCreateResultDF["bim2sim > plugins > PluginEnergyPlus > 
bim2sim_energyplus > task >  
 CreateResultDF"]
  extCreateResultDF(" This ITask creates a result dataframe for
EnergyPlus BEPS simulations See detailed
explanation in the run function below. " )
 end

stateCreateResultDF[("state
 (reads/touches)")]
    
stateCreateResultDF -- idf, sim_results_path, elements --> tCreateResultDF

tCreateResultDF -- df_finals --> stateCreateResultDF

end
    
subgraph taskPlotBEPSResults["task PlotBEPSResults"]
 subgraph "" 

  tPlotBEPSResults["bim2sim > tasks > bps >  
 PlotBEPSResults"]
  extPlotBEPSResults(" Class for plotting results of BEPS. " )
 end

statePlotBEPSResults[("state
 (reads/touches)")]
    
statePlotBEPSResults -- df_finals, sim_results_path, ifc_files, elements --> tPlotBEPSResults
direction RL
end
    taskLoadIFC --> taskCheckIfc 
taskCheckIfc --> taskCreateElementsOnIfcTypes 
taskCreateElementsOnIfcTypes --> taskCreateSpaceBoundaries 
taskCreateSpaceBoundaries --> taskAddSpaceBoundaries2B 
taskAddSpaceBoundaries2B --> taskCorrectSpaceBoundaries 
taskCorrectSpaceBoundaries --> taskCreateRelations 
taskCreateRelations --> taskDisaggregationCreationAndTypeCheck 
taskDisaggregationCreationAndTypeCheck --> taskEnrichMaterial 
taskEnrichMaterial --> taskEnrichUseConditions 
taskEnrichUseConditions --> taskWeather 
taskWeather --> taskCreateIdf 
taskCreateIdf --> taskIdfPostprocessing 
taskIdfPostprocessing --> taskExportIdfForCfd 
taskExportIdfForCfd --> taskSerializeElements 
taskSerializeElements --> taskRunEnergyPlusSimulation 
taskRunEnergyPlusSimulation --> taskCreateResultDF 
taskCreateResultDF --> taskPlotBEPSResults 
