---
title: plugin LCA
---
flowchart TB
    
subgraph taskLoadIFC["task LoadIFC"]
 subgraph "" 

  tLoadIFC["bim2sim > tasks > common >  
 LoadIFC"]
  extLoadIFC(" Load all IFC files from PROJECT. " )
 end

stateLoadIFC[("state
 (reads/touches)")]
    
tLoadIFC -- ifc_files --> stateLoadIFC

end
    
subgraph taskCreateElementsOnIfcTypes["task CreateElementsOnIfcTypes"]
 subgraph "" 

  tCreateElementsOnIfcTypes["bim2sim > tasks > common >  
 CreateElementsOnIfcTypes"]
  extCreateElementsOnIfcTypes(" Create bim2sim elements based on information of
IFC types. " )
 end

stateCreateElementsOnIfcTypes[("state
 (reads/touches)")]
    
stateCreateElementsOnIfcTypes -- ifc_files --> tCreateElementsOnIfcTypes

tCreateElementsOnIfcTypes -- elements, _initial_elements, ifc_files --> stateCreateElementsOnIfcTypes

end
    
subgraph taskCreateRelations["task CreateRelations"]
 subgraph "" 

  tCreateRelations["bim2sim > tasks > common >  
 CreateRelations"]
  extCreateRelations(" Relations of elements, run() method holds detailed
information. " )
 end

stateCreateRelations[("state
 (reads/touches)")]
    
stateCreateRelations -- elements --> tCreateRelations
direction RL
end
    
subgraph taskEnrichMaterial["task EnrichMaterial"]
 subgraph "" 

  tEnrichMaterial["bim2sim > tasks > bps >  
 EnrichMaterial"]
  extEnrichMaterial(" Enriches material properties that were recognized
as invalid LOD. " )
 end

stateEnrichMaterial[("state
 (reads/touches)")]
    
stateEnrichMaterial -- elements --> tEnrichMaterial
direction RL
end
    
subgraph taskExportLCA["task ExportLCA"]
 subgraph "" 

  tExportLCA["bim2sim > plugins > PluginLCA > 
bim2sim_lca > task >  
 ExportLCA"]
  extExportLCA(" Exports a CSV file with all relevant quantities of
the BIM model. " )
 end

stateExportLCA[("state
 (reads/touches)")]
    
stateExportLCA -- ifc_files, elements --> tExportLCA
direction RL
end
    taskLoadIFC --> taskCreateElementsOnIfcTypes 
taskCreateElementsOnIfcTypes --> taskCreateRelations 
taskCreateRelations --> taskEnrichMaterial 
taskEnrichMaterial --> taskExportLCA 
