FROM registry.git-ce.rwth-aachen.de/ebc/projects/ebc0438_bmwi_bim2sim_ges/bim2sim-coding/environment:development

## CFD part
RUN apt-get install -y git cmake gcc g++ tcllib tklib tcl-dev tk-dev libfreetype6-dev libxt-dev libxmu-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libfreeimage-dev libtbb-dev qt5-default libboost-all-dev libxml2-dev


# RUN cd /tmp && git clone https://github.com/Open-Cascade-SAS/OCCT && cd OCCT && mkdir build

RUN cd /tmp && git clone https://github.com/bimworld/occ.git && cd occ && unzip opencascade-7.5.3.zip && cd opencascade-7.5.3

WORKDIR /tmp/occ/opencascade-7.5.3/build
RUN cmake .. && make -j8 && make install

RUN cd /tmp && git clone --branch v0.6.0 https://github.com/IfcOpenShell/IfcOpenShell.git  && cd IfcOpenShell && mkdir build
WORKDIR /tmp/IfcOpenShell/build
RUN cmake ../cmake -DOCC_INCLUDE_DIR=/usr/local/include/opencascade -DCOLLADA_SUPPORT=OFF -DBUILD_IFCPYTHON=OFF
RUN make -j8
RUN make install
