FROM registry.git-ce.rwth-aachen.de/ebc/projects/ebc0438_bmwi_bim2sim_ges/bim2sim-coding/environment:development

## CFD part
RUN apt-get install -y git cmake gcc g++ tcllib tklib tcl-dev tk-dev libfreetype6-dev libxt-dev libxmu-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libfreeimage-dev libtbb-dev qt5-default libboost-all-dev libxml2-dev


# RUN cd /tmp && git clone https://github.com/Open-Cascade-SAS/OCCT && cd OCCT && mkdir build

RUN cd /tmp && git clone -b master https://github.com/bimworld/occ.git && cd occ && unzip opencascade-7.5.3.zip && cd opencascade-7.5.3

WORKDIR /tmp/occ/opencascade-7.5.3/build
RUN cmake .. -Wno-dev -DBUILD_DOC_Overview=OFF -DBUILD_Inspector=OFF -DBUILD_LIBRARY_TYPE=Shared -DBUILD_RESOURCES=OFF -DBUILD_SAMPLES_QT=OFF -DBUILD_USE_PCH=OFF -DBUILD_YACCLEX=OFF -DCMAKE_BUILD_TYPE=Release -DUSE_TBB=ON -DUSE_FREEIMAGE=ON && make -j8 && make install

RUN cd /tmp && git clone --branch v0.6.0 https://github.com/IfcOpenShell/IfcOpenShell.git  && cd IfcOpenShell && mkdir build
WORKDIR /tmp/IfcOpenShell/build
RUN cmake ../cmake -Wno-dev -DOCC_INCLUDE_DIR=/usr/local/include/opencascade -DBUILD_CONVERT=OFF -DBUILD_DOCUMENTATION=OFF -DBUILD_EXAMPLES=OFF -DBUILD_GEOMSERVER=OFF -DBUILD_CONVERT=OFF -DBUILD_PACKAGE=OFF -DCOLLADA_SUPPORT=OFF -DGLTF_SUPPORT=OFF -DBUILD_IFCPYTHON=OFF -DCMAKE_BUILD_TYPE=Release -DENABLE_BUILD_OPTIMIZATIONS=ON -DIFCXML_SUPPORT=OFF -DUSE_MMAP=OFF -DUSE_VLD=OFF -DBUILD_SHARED_LIBS=ON
# RUN cmake ../cmake -DOCC_INCLUDE_DIR=/usr/local/include/opencascade -DCOLLADA_SUPPORT=OFF -DBUILD_IFCPYTHON=OFF
RUN make -j8
RUN make install

RUN apt-get -y install libpolyclipping-dev

WORKDIR /tmp
RUN git clone -b master https://github.com/bimworld/bim.git ifc2sb
WORKDIR /tmp/ifc2sb
RUN chmod +x IFC2SB

# Analyse
RUN qmake --version
RUN whereis qt5
RUN ldd IFC2SB

RUN ./IFC2SB -h
