FROM continuumio/miniconda3


WORKDIR /bim2sim

RUN apt-get update
RUN apt-get -y install unzip
RUN apt-get -y install libgl-dev 

# Copy files
COPY ./MainLib/requirements.txt .

RUN 	conda create -n env python=3.7
RUN		conda update -n base -c defaults conda
RUN 	echo "source activate env" > ~/.bashrc
ENV 	PATH /opt/conda/envs/env/bin:$PATH
SHELL 	["conda", "run", "-n", "env", "/bin/bash", "-c"]

# install needed packages

RUN pip install -r ./requirements.txt

# install needed packages

## install pythonocc via conda
RUN /opt/conda/bin/conda install --yes --freeze-installed \
	    -c dlr-sc pythonocc-core=7.4.1 \
	    nomkl \
	&& /opt/conda/bin/conda clean -afy \
	&& find /opt/conda/ -follow -type f -name '*.a' -delete \
	&& find /opt/conda/ -follow -type f -name '*.pyc' -delete \
	&& find /opt/conda/ -follow -type f -name '*.js.map' -delete

## install ifcopenshell via existing file
RUN wget -O /tmp/ifcopenshell.zip https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-37-v0.6.0-ff7219b-linux64.zip \
&& unzip '/tmp/ifcopenshell.zip' -d /opt/conda/envs/env/lib/python3.7/site-packages/ && rm /tmp/ifcopenshell.zip || true ;


## install occ utils via existing file 
RUN wget -O /tmp/occ-utils.zip https://github.com/tpaviot/pythonocc-utils/archive/refs/heads/master.zip \
&& unzip '/tmp/occ-utils.zip' -d /tmp/occ-utils || true \
&& mv /tmp/occ-utils/pythonocc-utils-master/OCCUtils /opt/conda/envs/env/lib/python3.7/site-packages/ ;


# Set Pythonpath
ENV PYTHONPATH "${PYTHONPATH}:/bim2sim/MainLib"
ENV PYTHONPATH "${PYTHONPATH}:/bim2sim/PluginEnergyPlus"
ENV PYTHONPATH "${PYTHONPATH}:/bim2sim/PluginCFD"
ENV PYTHONPATH "${PYTHONPATH}:/bim2sim/PluginAixLib"
ENV PYTHONPATH "${PYTHONPATH}:/bim2sim/PluginHKESim"
ENV PYTHONPATH "${PYTHONPATH}:/bim2sim/PluginTEASER"
