name: bim2sim_coding
channels:
  - conda-forge
  - defaults

dependencies:
  - ifcopenshell=v0.6.0
  - pip:
    - docopt
    - matplotlib
    - numpy
    - python-dateutil
    - mako
    - networkx>=2.2
    - pint
    - rpyc
