stages:
  - build_conda_base
  - release_conda_base
  - build_conda_tool
  - release_conda_tool
  - build_conda_total
  - release_conda_total

variables:
  BIM2SIM_VERSION: ""
  BIM2SIM_NAME:  "bim2sim"


.conda_build:
  image: continuumio/miniconda3
  script:
    - apt update
    - apt install libgl1 -y
    - conda install conda-build git conda-verify -y
    - mkdir conda-bld
    - conda config --add channels bim2sim
    - conda build conda_recipe/$PATH/meta.yaml -c conda-forge --output-folder conda-bld/ --python 3.9
  retry:
    max: 2
    when: runner_system_failure
  artifacts:
    expire_in: 1 hour
    paths:
      - conda-bld
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - if: $CI_COMMIT_BRANCH == "development"
      variables:
        BIM2SIM_VERSION: "_dev"
      when: always
    - if: $CI_COMMIT_MESSAGE =~ /ci_build/
      variables:
        BIM2SIM_VERSION: "_dev"
      when: always

conda_build_bim2sim:base:
    stage: build_conda_base
    variables:
        BIM2SIM_NAME: "bim2sim"
        PATH: "basic_build"
    extends: .conda_build
    rules:
      - if: $CI_COMMIT_MESSAGE =~ /build_base_dev/
        variables:
          BIM2SIM_VERSION: "_dev"
        when: always
      - if: $CI_COMMIT_MESSAGE =~ /build_base_main/
        when: always

build_conda_tool:aixlib:
    stage: build_conda_tool
    variables:
        BIM2SIM_NAME: "bim2sim_aixlib"
        PATH: "plugins/PluginAixLib"
    extends: .conda_build
    rules:
      - if: $CI_COMMIT_MESSAGE =~ /build_tool_dev/
        variables:
          BIM2SIM_VERSION: "_dev"
        when: manual
      - if: $CI_COMMIT_MESSAGE =~ /build_tool_main/
        when: manual

build_conda_tool:cfd:
    stage: build_conda_tool
    variables:
        BIM2SIM_NAME: "bim2sim_cfd"
        PATH: "plugins/PluginCFD"
    extends: .conda_build
    rules:
      - if: $CI_COMMIT_MESSAGE =~ /build_tool_dev/
        variables:
          BIM2SIM_VERSION: "_dev"
        when: manual
      - if: $CI_COMMIT_MESSAGE =~ /build_tool_main/
        when: manual

build_conda_tool:energyplus:
    stage: build_conda_tool
    variables:
        BIM2SIM_NAME: "bim2sim_energyplus"
        PATH: "plugins/PluginEnergyPlus"
    extends: .conda_build
    rules:
      - if: $CI_COMMIT_MESSAGE =~ /build_tool_dev/
        variables:
          BIM2SIM_VERSION: "_dev"
        when: manual
      - if: $CI_COMMIT_MESSAGE =~ /build_tool_main/
        when: manual

build_conda_tool:hkesim:
    stage: build_conda_tool
    variables:
        BIM2SIM_NAME: "bim2sim_hkesim"
        PATH: "plugins/PluginHKESim"
    extends: .conda_build
    rules:
      - if: $CI_COMMIT_MESSAGE =~ /build_tool_dev/
        variables:
          BIM2SIM_VERSION: "_dev"
        when: manual
      - if: $CI_COMMIT_MESSAGE =~ /build_tool_main/
        when: manual

build_conda_tool:lca:
    stage: build_conda_tool
    variables:
      BIM2SIM_NAME: "bim2sim_lca"
      PATH: "plugins/PluginLCA"
    extends: .conda_build
    rules:
      - if: $CI_COMMIT_MESSAGE =~ /build_tool_dev/
        variables:
          BIM2SIM_VERSION: "_dev"
        when: manual
      - if: $CI_COMMIT_MESSAGE =~ /build_tool_main/
        when: manual

build_conda_tool:teaser:
    stage: build_conda_tool
    variables:
        BIM2SIM_NAME: "bim2sim_teaser"
        PATH: "plugins/PluginTEASER"
    extends: .conda_build
    rules:
      - if: $CI_COMMIT_MESSAGE =~ /build_tool_dev/
        variables:
          BIM2SIM_VERSION: "_dev"
        when: manual
      - if: $CI_COMMIT_MESSAGE =~ /build_tool_main/
        when: manual

build_conda_bim2sim:total:
    stage: build_conda_total
    variables:
        BIM2SIM_NAME: "bim2sim_total"
        PATH: "total"
    extends: .conda_build



.conda_release:
  image: continuumio/miniconda3
  script:
    - apt update
    - apt install libgl1 -y
    - conda install conda-build git conda-verify -y
    - conda install anaconda -y
    - anaconda login --username bim2sim --password $CONDA_TOKEN
    - conda update --all
    - conda install conda-build anaconda-client
    - conda convert -p osx-64 conda-bld/linux-64/bim2sim-* --output-dir conda-bld/ -f
    - conda convert -p osx-arm64 conda-bld/linux-64/bim2sim-* --output-dir conda-bld/ -f
    - conda convert -p win-64 conda-bld/linux-64/bim2sim-* --output-dir conda-bld/ -f
    - anaconda upload conda-bld/linux-64/bim2sim-* --force
    - anaconda upload conda-bld/osx-64/bim2sim-* --force
    - anaconda upload conda-bld/win-64/bim2sim-* --force
  retry:
    max: 2
    when: runner_system_failure
  artifacts:
    expire_in: 1 hour
    paths:
      - conda-bld
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - if: $CI_COMMIT_BRANCH == "development"
      when: always
    - if: $CI_COMMIT_MESSAGE =~ /ci_build/
      when: manual

release_conda_bim2sim:base:
  stage: release_conda_base
  dependencies:
    - conda_build_bim2sim:base
  extends: .conda_release
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /build_base_dev/
      when: manual
    - if: $CI_COMMIT_MESSAGE =~ /build_base_main/
      when: manual

release_conda_tool:aixlib:
  stage: release_conda_tool
  dependencies:
    - build_conda_tool:aixlib
  extends: .conda_release
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /build_tool_dev/
      when: manual
    - if: $CI_COMMIT_MESSAGE =~ /build_tool_main/
      when: manual

release_conda_tool:cfd:
  stage: release_conda_tool
  dependencies:
    - build_conda_tool:cfd
  extends: .conda_release
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /build_tool_dev/
      when: manual
    - if: $CI_COMMIT_MESSAGE =~ /build_tool_main/
      when: manual



release_conda_tool:energyplus:
  stage: release_conda_tool
  dependencies:
    - build_conda_tool:energyplus
  extends: .conda_release
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /build_tool_dev/
      when: manual
    - if: $CI_COMMIT_MESSAGE =~ /build_tool_main/
      when: manual


release_conda_tool:hkesim:
  stage: release_conda_tool
  dependencies:
    - build_conda_tool:hkesim
  extends: .conda_release
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /build_tool_dev/
      when: manual
    - if: $CI_COMMIT_MESSAGE =~ /build_tool_main/
      when: manual


release_conda_tool:lca:
  stage: release_conda_tool
  dependencies:
    - build_conda_tool:lca
  extends: .conda_release
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /build_tool_dev/
      when: manual
    - if: $CI_COMMIT_MESSAGE =~ /build_tool_main/
      when: manual


release_conda_tool:teaser:
  stage: release_conda_tool
  dependencies:
    - build_conda_tool:teaser
  extends: .conda_release
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /build_tool_dev/
      when: manual
    - if: $CI_COMMIT_MESSAGE =~ /build_tool_main/
      when: manual

release_conda_bim2sim:total:
  stage: release_conda_tool
  dependencies:
    - build_conda_bim2sim:total
  extends: .conda_release


