stages:
  - build_conda_base
  - release_conda_base
  - build_conda_plugin
  - release_conda_plugin
  - build_conda_total
  - release_conda_total

variables:
  BIM2SIM_FLAG: ""
  BIM2SIM_NAME:  "bim2sim"

.conda_build_rules:main:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: on_success
    - if: $CI_COMMIT_MESSAGE =~ /ci_build_main/
      when: on_success
    - if: $CI_COMMIT_MESSAGE =~ /ci_build_conda_main/
      when: on_success

.conda_build_rules:dev:
  rules:
    - if: $CI_COMMIT_BRANCH == "development"
      when: on_success
    - if: $CI_COMMIT_MESSAGE =~ /ci_build_dev/
      when: on_success
    - if: $CI_COMMIT_MESSAGE =~ /ci_build_conda_dev/
      when: on_success

.conda_build_rules:nightly:
  rules:
    - if: $CI_COMMIT_BRANCH == "development" && $CI_COMMIT_MESSAGE =~ /nightly_build_dev/
      when: on_success

.conda_build:
  image: continuumio/miniconda3
  script:
    - apt update
    - apt upgrade -y
    - apt install libgl1 -y
    - conda install conda-build git conda-verify anaconda anaconda-client -y
    - conda update --all  -y
    - conda config --set channel_priority flexible
    - mkdir -p conda-bld/$BIM2SIM_NAME
    - conda config --add channels dsdale24
    - conda config --add channels conda-forge
    - conda config --add channels bim2sim
    # conda config --add channels auto
    - conda config --add channels anaconda
    # conda build $CONDA_FILE -c conda-forge --output-folder conda-bld --python 3.9
    - conda build $CONDA_FILE  --output-folder conda-bld --python 3.9
  retry:
    max: 2
    when: runner_system_failure
  artifacts:
    expire_in: 1 hour
    paths:
      - conda-bld


# [Build Conda Base]
conda_build_bim2sim:base:main:
    stage: build_conda_base
    variables:
        BIM2SIM_NAME: "bim2sim"
        CONDA_FILE:  "conda_recipe/basic_build/meta.yaml"
        BIM2SIM_FLAG: ""
    extends: .conda_build
    rules:
      - !reference [.conda_build_rules:main, rules]
      - if: $CI_COMMIT_MESSAGE =~ /ci_build_base_main/
        when: on_success

conda_build_bim2sim:base:dev:
    stage: build_conda_base
    variables:
        BIM2SIM_NAME: "bim2sim"
        CONDA_FILE:  "conda_recipe/basic_build/meta.yaml"
        BIM2SIM_FLAG: ".dev"
    extends: .conda_build
    rules:
      - !reference [.conda_build_rules:dev, rules]
      - if: $CI_COMMIT_MESSAGE =~ /ci_build_base_dev/
        when: on_success

conda_build_bim2sim:base:nightly:
    stage: build_conda_base
    variables:
        BIM2SIM_NAME: "bim2sim"
        CONDA_FILE:  "conda_recipe/basic_build/meta.yaml"
        BIM2SIM_FLAG: ".nightly"
    extends: .conda_build
    rules:
      - !reference [.conda_build_rules:nightly, rules]

# [Build Conda Plugins]
.conda_build_rules:plugin:main:
  rules:
     - !reference [.conda_build_rules:main, rules]
     - if: $CI_COMMIT_MESSAGE =~ /ci_build_plugin_main/
       when: on_success

.conda_build_rules:plugin:dev:
  rules:
     - !reference [.conda_build_rules:dev, rules]
     - if: $CI_COMMIT_MESSAGE =~ /ci_build_plugin_dev/
       when: on_success

# [Build Conda aixlib plugins]
build_conda_plugin:aixlib:main:
    stage: build_conda_plugin
    variables:
        BIM2SIM_NAME: "bim2sim_aixlib"
        CONDA_FILE: "conda_recipe/plugins/PluginAixLib/meta.yaml"
        BIM2SIM_FLAG: ""
    extends: .conda_build
    rules:
      - !reference [.conda_build_rules:plugin:main, rules]

build_conda_plugin:aixlib:dev:
    stage: build_conda_plugin
    variables:
        BIM2SIM_NAME: "bim2sim_aixlib"
        CONDA_FILE: "conda_recipe/plugins/PluginAixLib/meta.yaml"
        BIM2SIM_FLAG: ".dev"
    extends: .conda_build
    rules:
      - !reference [.conda_build_rules:plugin:dev, rules]

build_conda_plugin:aixlib:nightly:
    stage: build_conda_plugin
    variables:
        BIM2SIM_NAME: "bim2sim_aixlib"
        CONDA_FILE: "conda_recipe/plugins/PluginAixLib/meta.yaml"
        BIM2SIM_FLAG: ".nightly"
    extends: .conda_build
    rules:
      - !reference [.conda_build_rules:nightly, rules]

# [Build Conda cfd plugins]
build_conda_plugin:cfd:main:
    stage: build_conda_plugin
    variables:
        BIM2SIM_NAME: "bim2sim_cfd"
        CONDA_FILE: "conda_recipe/plugins/PluginCFD/meta.yaml"
        BIM2SIM_FLAG: ""
    extends: .conda_build
    rules:
      - !reference [ .conda_build_rules:plugin:main, rules ]

build_conda_plugin:cfd:dev:
    stage: build_conda_plugin
    variables:
        BIM2SIM_NAME: "bim2sim_cfd"
        CONDA_FILE: "conda_recipe/plugins/PluginCFD/meta.yaml"
        BIM2SIM_FLAG: ".dev"
    extends: .conda_build
    rules:
      - !reference [.conda_build_rules:plugin:dev, rules]

build_conda_plugin:cfd:nightly:
    stage: build_conda_plugin
    variables:
        BIM2SIM_NAME: "bim2sim_cfd"
        CONDA_FILE: "conda_recipe/plugins/PluginCFD/meta.yaml"
        BIM2SIM_FLAG: ".nightly"
    extends: .conda_build
    rules:
      - !reference [  .conda_build_rules:nightly, rules]

# [Build Conda energyplus plugins]
build_conda_plugin:energyplus:main:
    stage: build_conda_plugin
    variables:
        BIM2SIM_NAME: "bim2sim_energyplus"
        CONDA_FILE: "conda_recipe/plugins/PluginEnergyPlus/meta.yaml"
        BIM2SIM_FLAG: ""
    extends: .conda_build
    rules:
      - !reference [.conda_build_rules:plugin:main, rules ]

build_conda_plugin:energyplus:dev:
    stage: build_conda_plugin
    variables:
        BIM2SIM_NAME: "bim2sim_energyplus"
        CONDA_FILE: "conda_recipe/plugins/PluginEnergyPlus/meta.yaml"
        BIM2SIM_FLAG: ".dev"
    extends: .conda_build
    rules:
      - !reference [.conda_build_rules:plugin:dev, rules]

build_conda_plugin:energyplus:nightly:
    stage: build_conda_plugin
    variables:
        BIM2SIM_NAME: "bim2sim_energyplus"
        CONDA_FILE: "conda_recipe/plugins/PluginEnergyPlus/meta.yaml"
        BIM2SIM_FLAG: ".nightly"
    extends: .conda_build
    rules:
      - !reference [.conda_build_rules:nightly, rules]

# [Build Conda hkesim plugins]

build_conda_plugin:hkesim:main:
    stage: build_conda_plugin
    variables:
        BIM2SIM_NAME: "bim2sim_hkesim"
        CONDA_FILE: "conda_recipe/plugins/PluginHKESim/meta.yaml"
        BIM2SIM_FLAG: ""
    extends: .conda_build
    rules:
      - !reference [ .conda_build_rules:plugin:main, rules ]

build_conda_plugin:hkesim:dev:
    stage: build_conda_plugin
    variables:
        BIM2SIM_NAME: "bim2sim_hkesim"
        CONDA_FILE: "conda_recipe/plugins/PluginHKESim/meta.yaml"
        BIM2SIM_FLAG: ".dev"
    extends: .conda_build
    rules:
      - !reference [.conda_build_rules:plugin:dev, rules]

build_conda_plugin:hkesim:nightly:
    stage: build_conda_plugin
    variables:
        BIM2SIM_NAME: "bim2sim_hkesim"
        CONDA_FILE: "conda_recipe/plugins/PluginHKESim/meta.yaml"
        BIM2SIM_FLAG: ".nightly"
    extends: .conda_build
    rules:
      - !reference [.conda_build_rules:nightly, rules]

# [Build Conda lca plugins]

build_conda_plugin:lca:main:
    stage: build_conda_plugin
    variables:
      BIM2SIM_NAME: "bim2sim_lca"
      CONDA_FILE: "conda_recipe/plugins/PluginLCA/meta.yaml"
      BIM2SIM_FLAG: ""
    extends: .conda_build
    rules:
      - !reference [.conda_build_rules:plugin:main, rules ]

build_conda_plugin:lca:dev:
    stage: build_conda_plugin
    variables:
      BIM2SIM_NAME: "bim2sim_lca"
      CONDA_FILE: "conda_recipe/plugins/PluginLCA/meta.yaml"
      BIM2SIM_FLAG: ".dev"
    extends: .conda_build
    rules:
      - !reference [.conda_build_rules:plugin:dev, rules]

build_conda_plugin:lca:nightly:
    stage: build_conda_plugin
    variables:
      BIM2SIM_NAME: "bim2sim_lca"
      CONDA_FILE: "conda_recipe/plugins/PluginLCA/meta.yaml"
      BIM2SIM_FLAG: ".nightly"
    extends: .conda_build
    rules:
      - !reference [.conda_build_rules:nightly, rules]

# [Build Conda teaser plugins]
build_conda_plugin:teaser:main:
    stage: build_conda_plugin
    variables:
        BIM2SIM_NAME: "bim2sim_teaser"
        CONDA_FILE: "conda_recipe/plugins/PluginTeaser/meta.yaml"
        BIM2SIM_FLAG: ""
    extends: .conda_build
    rules:
      - !reference [.conda_build_rules:plugin:main, rules ]

build_conda_plugin:teaser:dev:
    stage: build_conda_plugin
    variables:
        BIM2SIM_NAME: "bim2sim_teaser"
        CONDA_FILE: "conda_recipe/plugins/PluginTeaser/meta.yaml"
        BIM2SIM_FLAG: ".dev"
    extends: .conda_build
    rules:
      - !reference [.conda_build_rules:plugin:dev, rules]

build_conda_plugin:teaser:nightly:
    stage: build_conda_plugin
    variables:
        BIM2SIM_NAME: "bim2sim_teaser"
        CONDA_FILE: "conda_recipe/plugins/PluginTeaser/meta.yaml"
        BIM2SIM_FLAG: ".nightly"
    extends: .conda_build
    rules:
      - !reference [.conda_build_rules:nightly, rules]

# [Build Conda total]

build_conda_bim2sim:total:main:
    stage: build_conda_total
    variables:
        BIM2SIM_NAME: "bim2sim"
        CONDA_FILE: "conda_recipe/total/meta.yaml"
        BIM2SIM_FLAG: ""
    extends: .conda_build
    rules:
      - !reference [.conda_build_rules:main, rules]
      - if: $CI_COMMIT_MESSAGE =~ /ci_build_total_main/
        when: on_success

build_conda_bim2sim:total:dev:
    stage: build_conda_total
    variables:
        BIM2SIM_NAME: "bim2sim"
        CONDA_FILE: "conda_recipe/total/meta.yaml"
        BIM2SIM_FLAG: ".dev"
    extends: .conda_build
    rules:
      - !reference [.conda_build_rules:dev, rules]
      - if: $CI_COMMIT_MESSAGE =~ /ci_build_total_dev/
        when: on_success

build_conda_bim2sim:total:nightly:
    stage: build_conda_total
    variables:
        BIM2SIM_NAME: "bim2sim"
        CONDA_FILE: "conda_recipe/total/meta.yaml"
        BIM2SIM_FLAG: ".nightly"
    extends: .conda_build
    rules:
      - !reference [.conda_build_rules:nightly, rules]

# [release conda]
.conda_release:
  image: continuumio/miniconda3
  script:
    - apt update
    - apt upgrade -y
    - apt install libgl1 -y
    - conda install conda-build git conda-verify anaconda anaconda-client -y
    - conda update --all  -y
    - conda config  --set channel_priority strict
    - conda config --describe channel_priority
    # pip install cryptography==38.0.4
    - anaconda logout
    - anaconda login --username bim2sim --password $CONDA_TOKEN --hostname $CI_JOB_ID

    - conda convert -p osx-64 conda-bld/linux-64/$BIM2SIM_NAME-* --output-dir conda-bld -f
    - anaconda upload conda-bld/osx-64/$BIM2SIM_NAME-* --force

    # conda convert -p osx-arm64 conda-bld/$BIM2SIM_NAME/linux-64/$BIM2SIM_NAME-* --output-dir conda-bld/$BIM2SIM_NAME -f
    # anaconda upload conda-bld/$BIM2SIM_NAME/osx-arm64/$BIM2SIM_NAME-* --force

    - conda convert -p win-64 conda-bld/linux-64/$BIM2SIM_NAME-* --output-dir conda-bld -f
    - anaconda upload conda-bld/win-64/$BIM2SIM_NAME-* --force

    - conda convert -p linux-64 conda-bld/linux-64/$BIM2SIM_NAME-* --output-dir conda-bld -f
    - anaconda upload conda-bld/linux-64/$BIM2SIM_NAME-* --force

    # conda convert -p linux-aarch64 conda-bld/$BIM2SIM_NAME/linux-64/$BIM2SIM_NAME-* --output-dir conda-bld/$BIM2SIM_NAME -f
    # anaconda upload conda-bld/$BIM2SIM_NAME/linux-aarch64/$BIM2SIM_NAME-* --force
    - anaconda logout
  retry:
    max: 2
    when: runner_system_failure

.conda_release_rules:main:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: on_success
    - if: $CI_COMMIT_MESSAGE =~ /ci_build_main/
      when: manual
    - if: $CI_COMMIT_MESSAGE =~ /ci_build_conda_main/
      when: manual


.conda_release_rules:dev:
  rules:
    - if: $CI_COMMIT_BRANCH == "development"
      when: on_success
    - if: $CI_COMMIT_MESSAGE =~ /ci_build_dev/
      when: manual
    - if: $CI_COMMIT_MESSAGE =~ /ci_build_conda_dev/
      when: manual

.conda_release_rules:nightly:
  rules:
    - if: $CI_COMMIT_BRANCH == "development"
      when: on_success
    - if: $CI_COMMIT_MESSAGE =~ /ci_build_dev/
      when: manual
    - if: $CI_COMMIT_MESSAGE =~ /ci_build_conda_dev/
      when: manual


.conda_release_rules:plugin:main:
  rules:
     - !reference [.conda_release_rules:main, rules]
     - if: $CI_COMMIT_MESSAGE =~ /ci_build_plugin_main/
       when: manual

.conda_release_rules:plugin:dev:
  rules:
     - !reference [.conda_release_rules:dev, rules]
     - if: $CI_COMMIT_MESSAGE =~ /ci_build_plugin_dev/
       when: manual



# [release base conda image]
release_conda_bim2sim:base:main:
  stage: release_conda_base
  variables:
    BIM2SIM_NAME: "bim2sim"
  dependencies:
    - conda_build_bim2sim:base:main
  extends: .conda_release
  rules:
    - !reference [.conda_release_rules:main, rules ]
    - if: $CI_COMMIT_MESSAGE =~ /ci_build_base_main/
      when: manual

release_conda_bim2sim:base:dev:
  stage: release_conda_base
  variables:
    BIM2SIM_NAME: "bim2sim"
  dependencies:
    - conda_build_bim2sim:base:dev
  extends: .conda_release
  rules:
    - !reference [.conda_release_rules:dev, rules ]
    - if: $CI_COMMIT_MESSAGE =~ /ci_build_base_dev/
      when: manual

release_conda_bim2sim:base:nightly:
  stage: release_conda_base
  variables:
    BIM2SIM_NAME: "bim2sim"
  dependencies:
    - conda_build_bim2sim:base:nightly
  extends: .conda_release
  rules:
    - !reference [.conda_build_rules:nightly, rules ]


# [release plugin conda image]
# [release aixlib plugin conda]
release_conda_plugin:aixlib:main:
  stage: release_conda_plugin
  variables:
    BIM2SIM_NAME: "bim2sim_aixlib"
  dependencies:
    - build_conda_plugin:aixlib:main
  extends: .conda_release
  rules:
    - !reference [.conda_release_rules:plugin:main, rules ]


release_conda_plugin:aixlib:dev:
  stage: release_conda_plugin
  variables:
    BIM2SIM_NAME: "bim2sim_aixlib"
  dependencies:
    - build_conda_plugin:aixlib:dev
  extends: .conda_release
  rules:
    - !reference [.conda_release_rules:plugin:dev, rules ]

release_conda_plugin:aixlib:nightly:
  stage: release_conda_plugin
  variables:
    BIM2SIM_NAME: "bim2sim_aixlib"
  dependencies:
    - build_conda_plugin:aixlib:nightly
  extends: .conda_release
  rules:
    - !reference [.conda_build_rules:nightly, rules]


# [release cfd plugin conda]

release_conda_plugin:cfd:main:
  stage: release_conda_plugin
  variables:
    BIM2SIM_NAME: "bim2sim_cfd"
  dependencies:
    - build_conda_plugin:cfd:main
  extends: .conda_release
  rules:
    - !reference [.conda_release_rules:plugin:main, rules ]

release_conda_plugin:cfd:dev:
  stage: release_conda_plugin
  variables:
    BIM2SIM_NAME: "bim2sim_cfd"
  dependencies:
    - build_conda_plugin:cfd:dev
  extends: .conda_release
  rules:
    - !reference [.conda_release_rules:plugin:dev, rules ]

release_conda_plugin:cfd:nightly:
  stage: release_conda_plugin
  variables:
    BIM2SIM_NAME: "bim2sim_cfd"
  dependencies:
    - build_conda_plugin:cfd:nightly
  extends: .conda_release
  rules:
    - !reference [.conda_build_rules:nightly, rules ]

 # [release energyplus plugin conda]

release_conda_plugin:energyplus:main:
  stage: release_conda_plugin
  variables:
    BIM2SIM_NAME: "bim2sim_energyplus"
  dependencies:
    - build_conda_plugin:energyplus:main
  extends: .conda_release
  rules:
    - !reference [.conda_release_rules:plugin:main, rules ]

release_conda_plugin:energyplus:dev:
  stage: release_conda_plugin
  variables:
    BIM2SIM_NAME: "bim2sim_energyplus"
  dependencies:
    - build_conda_plugin:energyplus:dev
  extends: .conda_release
  rules:
    - !reference [.conda_release_rules:plugin:dev, rules ]

release_conda_plugin:energyplus:nightly:
  stage: release_conda_plugin
  variables:
    BIM2SIM_NAME: "bim2sim_energyplus"
  dependencies:
    - build_conda_plugin:energyplus:nightly
  extends: .conda_release
  rules:
    - !reference [.conda_build_rules:nightly, rules ]

 # [release hkesim plugin conda]

release_conda_plugin:hkesim:main:
  stage: release_conda_plugin
  variables:
    BIM2SIM_NAME: "bim2sim_hkesim"
  dependencies:
    - build_conda_plugin:hkesim:main
  extends: .conda_release
  rules:
    - !reference [.conda_release_rules:plugin:main, rules ]

release_conda_plugin:hkesim:dev:
  stage: release_conda_plugin
  variables:
    BIM2SIM_NAME: "bim2sim_hkesim"
  dependencies:
    - build_conda_plugin:hkesim:dev
  extends: .conda_release
  rules:
    - !reference [.conda_release_rules:plugin:dev, rules ]

release_conda_plugin:hkesim:nightly:
  stage: release_conda_plugin
  variables:
    BIM2SIM_NAME: "bim2sim_hkesim"
  dependencies:
    - build_conda_plugin:hkesim:nightly
  extends: .conda_release
  rules:
    - !reference [.conda_build_rules:nightly, rules ]

 # [release lca plugin conda]

release_conda_plugin:lca:main:
  stage: release_conda_plugin
  variables:
    BIM2SIM_NAME: "bim2sim_lca"
  dependencies:
    - build_conda_plugin:lca:main
  extends: .conda_release
  rules:
    - !reference [.conda_release_rules:plugin:main, rules ]

release_conda_plugin:lca:dev:
  stage: release_conda_plugin
  variables:
    BIM2SIM_NAME: "bim2sim_lca"
  dependencies:
    - build_conda_plugin:lca:dev
  extends: .conda_release
  rules:
    - !reference [.conda_release_rules:plugin:dev, rules ]

release_conda_plugin:lca:nightly:
  stage: release_conda_plugin
  variables:
    BIM2SIM_NAME: "bim2sim_lca"
  dependencies:
    - build_conda_plugin:lca:nightly
  extends: .conda_release
  rules:
    - !reference [.conda_build_rules:nightly, rules ]

 # [release teaser plugin conda]

release_conda_plugin:teaser:main:
  stage: release_conda_plugin
  variables:
    BIM2SIM_NAME: "bim2sim_teaser"
  dependencies:
    - build_conda_plugin:teaser:main
  extends: .conda_release
  rules:
    - !reference [.conda_release_rules:plugin:main, rules ]

release_conda_plugin:teaser:dev:
  stage: release_conda_plugin
  variables:
    BIM2SIM_NAME: "bim2sim_teaser"
  dependencies:
    - build_conda_plugin:teaser:dev
  extends: .conda_release
  rules:
    - !reference [.conda_release_rules:plugin:dev, rules ]

release_conda_plugin:teaser:nightly:
  stage: release_conda_plugin
  variables:
    BIM2SIM_NAME: "bim2sim_teaser"
  dependencies:
    - build_conda_plugin:teaser:nightly
  extends: .conda_release
  rules:
    - !reference [.conda_build_rules:nightly, rules ]

#  [release total bim2sim conda image]

release_conda_bim2sim:total:main:
  stage: release_conda_total
  variables:
    BIM2SIM_NAME: "bim2sim"
  dependencies:
    - build_conda_bim2sim:total:main
  extends: .conda_release
  rules:
    - !reference [ .conda_release_rules:main, rules ]
    - if: $CI_COMMIT_MESSAGE =~ /ci_build_total_main/
      when: manual

# [conda total]
release_conda_bim2sim:total:dev:
  stage: release_conda_total
  variables:
    BIM2SIM_NAME: "bim2sim"
  dependencies:
    - build_conda_bim2sim:total:dev
  extends: .conda_release
  rules:
    - !reference [ .conda_release_rules:dev, rules ]
    - if: $CI_COMMIT_MESSAGE =~ /ci_build_total_dev/
      when: manual

# [conda total]
release_conda_bim2sim:total:nightly:
  stage: release_conda_total
  variables:
    BIM2SIM_NAME: "bim2sim"
  dependencies:
    - build_conda_bim2sim:total:nightly
  extends: .conda_release
  rules:
    - !reference [ .conda_build_rules:nightly, rules ]
