stages:
  - conda_build_tool
  - conda_release_tool

variables:
  BIM2SIM_VERSION: ""

build_conda_tool:aixlib:
  image: continuumio/miniconda3
  stage: conda_build_tool
  script:
    - apt update
    - apt install libgl1 -y
    - conda install conda-build git conda-verify -y
    - mkdir conda-bld
    - conda build conda_recipe/plugins/PluginAixLib/meta.yaml -c conda-forge --output-folder conda-bld/ --python 3.9
  retry:
    max: 2
    when: runner_system_failure
  artifacts:
    expire_in: 1 hour
    paths:
      - conda-bld
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      variables:
        BIM2SIM_VERSION: "aixlib"
      when: always
    - if: $CI_COMMIT_BRANCH == "development"
      variables:
        BIM2SIM_VERSION: "aixlib_dev"
      when: always
    - if: $CI_COMMIT_MESSAGE =~ /ci_conda_build/
      variables:
        BIM2SIM_VERSION: "cfd_dev"
      when: manual

release_conda_tool:aixlib:
  image: continuumio/miniconda3
  stage: conda_release_tool
  script:
    - apt update
    - apt install libgl1 -y
    - conda install conda-build git conda-verify -y
    - conda install anaconda -y
    - anaconda login --username bim2sim --password $CONDA_TOKEN
    - conda update --all
    - conda install conda-build anaconda-client
    - conda convert -p osx-64 conda-bld/linux-64/bim2sim-* --output-dir conda-bld/ -f
    - conda convert -p osx-arm64 conda-bld/linux-64/bim2sim-* --output-dir conda-bld/ -f
    - conda convert -p win-64 conda-bld/linux-64/bim2sim-* --output-dir conda-bld/ -f
    - anaconda upload conda-bld/linux-64/bim2sim-* --force
    - anaconda upload conda-bld/osx-64/bim2sim-* --force
    - anaconda upload conda-bld/win-64/bim2sim-* --force
  retry:
    max: 2
    when: runner_system_failure
  dependencies:
    - build_conda_tool:aixlib
  artifacts:
    expire_in: 1 hour
    paths:
      - conda-bld
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - if: $CI_COMMIT_BRANCH == "development"
      when: always
    - if: $CI_COMMIT_MESSAGE =~ /ci_conda_build/
      when: manual


build_conda_tool:cfd:
  image: continuumio/miniconda3
  stage: conda_build_tool
  script:
    - apt update
    - apt install libgl1 -y
    - conda install conda-build git conda-verify -y
    - mkdir conda-bld
    - conda build conda_recipe/plugins/PluginCFD/meta.yaml -c conda-forge --output-folder conda-bld/ --python 3.9
  retry:
    max: 2
    when: runner_system_failure
  artifacts:
    expire_in: 1 hour
    paths:
      - conda-bld
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      variables:
        BIM2SIM_VERSION: "cfd"
      when: always
    - if: $CI_COMMIT_BRANCH == "development"
      variables:
        BIM2SIM_VERSION: "cfd_dev"
      when: always
    - if: $CI_COMMIT_MESSAGE =~ /ci_conda_build/
      variables:
        BIM2SIM_VERSION: "cfd_dev"
      when: manual

release_conda_tool:cfd:
  image: continuumio/miniconda3
  stage: conda_release_tool
  script:
    - apt update
    - apt install libgl1 -y
    - conda install conda-build git conda-verify -y
    - conda install anaconda -y
    - anaconda login --username bim2sim --password $CONDA_TOKEN
    - conda update --all
    - conda install conda-build anaconda-client
    - conda convert -p osx-64 conda-bld/linux-64/bim2sim-* --output-dir conda-bld/ -f
    - conda convert -p osx-arm64 conda-bld/linux-64/bim2sim-* --output-dir conda-bld/ -f
    - conda convert -p win-64 conda-bld/linux-64/bim2sim-* --output-dir conda-bld/ -f
    - anaconda upload conda-bld/linux-64/bim2sim-* --force
    - anaconda upload conda-bld/osx-64/bim2sim-* --force
    - anaconda upload conda-bld/win-64/bim2sim-* --force
  retry:
    max: 2
    when: runner_system_failure
  dependencies:
    - build_conda_tool:cfd
  artifacts:
    expire_in: 1 hour
    paths:
      - conda-bld
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - if: $CI_COMMIT_BRANCH == "development"
      when: always
    - if: $CI_COMMIT_MESSAGE =~ /ci_conda_build/
      when: manual

build_conda_tool:energyplus:
  image: continuumio/miniconda3
  stage: conda_build_tool
  script:
    - apt update
    - apt install libgl1 -y
    - conda install conda-build git conda-verify -y
    - mkdir conda-bld
    - conda build conda_recipe/plugins/PluginEnergyPlus/meta.yaml -c conda-forge --output-folder conda-bld/ --python 3.9
  retry:
    max: 2
    when: runner_system_failure
  artifacts:
    expire_in: 1 hour
    paths:
      - conda-bld
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      variables:
        BIM2SIM_VERSION: "energyplus"
      when: always
    - if: $CI_COMMIT_BRANCH == "development"
      variables:
        BIM2SIM_VERSION: "energyplus_dev"
      when: always
    - if: $CI_COMMIT_MESSAGE =~ /ci_conda_build/
      variables:
        BIM2SIM_VERSION: "energyplus_dev"
      when: manual

release_conda_tool:energyplus:
  image: continuumio/miniconda3
  stage: conda_release_tool
  script:
    - apt update
    - apt install libgl1 -y
    - conda install conda-build git conda-verify -y
    - conda install anaconda -y
    - anaconda login --username bim2sim --password $CONDA_TOKEN
    - conda update --all
    - conda install conda-build anaconda-client
    - conda convert -p osx-64 conda-bld/linux-64/bim2sim-* --output-dir conda-bld/ -f
    - conda convert -p osx-arm64 conda-bld/linux-64/bim2sim-* --output-dir conda-bld/ -f
    - conda convert -p win-64 conda-bld/linux-64/bim2sim-* --output-dir conda-bld/ -f
    - anaconda upload conda-bld/linux-64/bim2sim-* --force
    - anaconda upload conda-bld/osx-64/bim2sim-* --force
    - anaconda upload conda-bld/win-64/bim2sim-* --force
  retry:
    max: 2
    when: runner_system_failure
  dependencies:
    - build_conda_tool:energyplus
  artifacts:
    expire_in: 1 hour
    paths:
      - conda-bld
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - if: $CI_COMMIT_BRANCH == "development"
      when: always
    - if: $CI_COMMIT_MESSAGE =~ /ci_conda_build/
      when: manual


build_conda_tool:hkesim:
  image: continuumio/miniconda3
  stage: conda_build_tool
  script:
    - apt update
    - apt install libgl1 -y
    - conda install conda-build git conda-verify -y
    - mkdir conda-bld
    - conda build conda_recipe/plugins/PluginHKESim/meta.yaml -c conda-forge --output-folder conda-bld/ --python 3.9
  retry:
    max: 2
    when: runner_system_failure
  artifacts:
    expire_in: 1 hour
    paths:
      - conda-bld
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      variables:
        BIM2SIM_VERSION: "hkesim"
      when: always
    - if: $CI_COMMIT_BRANCH == "development"
      variables:
        BIM2SIM_VERSION: "hkesim_dev"
      when: always
    - if: $CI_COMMIT_MESSAGE =~ /ci_conda_build/
      variables:
        BIM2SIM_VERSION: "hkesim_dev"
      when: manual

release_conda_tool:hkesim:
  image: continuumio/miniconda3
  stage: conda_release_tool
  script:
    - apt update
    - apt install libgl1 -y
    - conda install conda-build git conda-verify -y
    - conda install anaconda -y
    - anaconda login --username bim2sim --password $CONDA_TOKEN
    - conda update --all
    - conda install conda-build anaconda-client
    - conda convert -p osx-64 conda-bld/linux-64/bim2sim-* --output-dir conda-bld/ -f
    - conda convert -p osx-arm64 conda-bld/linux-64/bim2sim-* --output-dir conda-bld/ -f
    - conda convert -p win-64 conda-bld/linux-64/bim2sim-* --output-dir conda-bld/ -f
    - anaconda upload conda-bld/linux-64/bim2sim-* --force
    - anaconda upload conda-bld/osx-64/bim2sim-* --force
    - anaconda upload conda-bld/win-64/bim2sim-* --force
  retry:
    max: 2
    when: runner_system_failure
  dependencies:
    - build_conda_tool:hkesim
  artifacts:
    expire_in: 1 hour
    paths:
      - conda-bld
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - if: $CI_COMMIT_BRANCH == "development"
      when: always
    - if: $CI_COMMIT_MESSAGE =~ /ci_conda_build/
      when: manual


build_conda_tool:lca:
  image: continuumio/miniconda3
  stage: conda_build_tool
  script:
    - apt update
    - apt install libgl1 -y
    - conda install conda-build git conda-verify -y
    - mkdir conda-bld
    - conda build conda_recipe/plugins/PluginLCA/meta.yaml -c conda-forge --output-folder conda-bld/ --python 3.9
  retry:
    max: 2
    when: runner_system_failure
  artifacts:
    expire_in: 1 hour
    paths:
      - conda-bld
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      variables:
        BIM2SIM_VERSION: "lca"
      when: always
    - if: $CI_COMMIT_BRANCH == "development"
      variables:
        BIM2SIM_VERSION: "lca_dev"
      when: always
    - if: $CI_COMMIT_MESSAGE =~ /ci_conda_build/
      variables:
        BIM2SIM_VERSION: "lca_dev"
      when: manual

release_conda_tool:lca:
  image: continuumio/miniconda3
  stage: conda_release_tool
  script:
    - apt update
    - apt install libgl1 -y
    - conda install conda-build git conda-verify -y
    - conda install anaconda -y
    - anaconda login --username bim2sim --password $CONDA_TOKEN
    - conda update --all
    - conda install conda-build anaconda-client
    - conda convert -p osx-64 conda-bld/linux-64/bim2sim-* --output-dir conda-bld/ -f
    - conda convert -p osx-arm64 conda-bld/linux-64/bim2sim-* --output-dir conda-bld/ -f
    - conda convert -p win-64 conda-bld/linux-64/bim2sim-* --output-dir conda-bld/ -f
    - anaconda upload conda-bld/linux-64/bim2sim-* --force
    - anaconda upload conda-bld/osx-64/bim2sim-* --force
    - anaconda upload conda-bld/win-64/bim2sim-* --force
  retry:
    max: 2
    when: runner_system_failure
  dependencies:
    - build_conda_tool:lca
  artifacts:
    expire_in: 1 hour
    paths:
      - conda-bld
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - if: $CI_COMMIT_BRANCH == "development"
      when: always
    - if: $CI_COMMIT_MESSAGE =~ /ci_conda_build/
      when: manual


build_conda_tool:teaser:
  image: continuumio/miniconda3
  stage: conda_build_tool
  script:
    - apt update
    - apt install libgl1 -y
    - conda install conda-build git conda-verify -y
    - mkdir conda-bld
    - conda build conda_recipe/plugins/PluginTeaser/meta.yaml -c conda-forge --output-folder conda-bld/ --python 3.9
  retry:
    max: 2
    when: runner_system_failure
  artifacts:
    expire_in: 1 hour
    paths:
      - conda-bld
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      variables:
        BIM2SIM_VERSION: "teaser"
      when: always
    - if: $CI_COMMIT_BRANCH == "development"
      variables:
        BIM2SIM_VERSION: "teaser_dev"
      when: always
    - if: $CI_COMMIT_MESSAGE =~ /ci_conda_build/
      variables:
        BIM2SIM_VERSION: "teaser_dev"
      when: manual

release_conda_tool:teaser:
  image: continuumio/miniconda3
  stage: conda_release_tool
  script:
    - apt update
    - apt install libgl1 -y
    - conda install conda-build git conda-verify -y
    - conda install anaconda -y
    - anaconda login --username bim2sim --password $CONDA_TOKEN
    - conda update --all
    - conda install conda-build anaconda-client
    - conda convert -p osx-64 conda-bld/linux-64/bim2sim-* --output-dir conda-bld/ -f
    - conda convert -p osx-arm64 conda-bld/linux-64/bim2sim-* --output-dir conda-bld/ -f
    - conda convert -p win-64 conda-bld/linux-64/bim2sim-* --output-dir conda-bld/ -f
    - anaconda upload conda-bld/linux-64/bim2sim-* --force
    - anaconda upload conda-bld/osx-64/bim2sim-* --force
    - anaconda upload conda-bld/win-64/bim2sim-* --force
  retry:
    max: 2
    when: runner_system_failure
  dependencies:
    - build_conda_tool:teaser
  artifacts:
    expire_in: 1 hour
    paths:
      - conda-bld
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - if: $CI_COMMIT_BRANCH == "development"
      when: always
    - if: $CI_COMMIT_MESSAGE =~ /ci_conda_build/
      when: manual
