stages:
  - build_conda_base
  - release_conda_base
  - build_conda_plugin
  - release_conda_plugin
  - build_conda_total
  - release_conda_total

variables:
  BIM2SIM_VERSION: ""
  BIM2SIM_NAME:  "bim2sim"

.conda_build:
  image: continuumio/miniconda3
  script:
    - apt update
    - apt install libgl1 -y
    - conda install conda-build git conda-verify -y
    - mkdir -p conda-bld
    - mkdir -p conda-bld/$BIM2SIM_NAME
    - conda config --add channels bim2sim
    - conda config --add channels dsdale24
    - conda build $CONDA_FILE -c conda-forge --output-folder conda-bld/$BIM2SIM_NAME --python 3.9
  retry:
    max: 2
    when: runner_system_failure
  artifacts:
    expire_in: 1 hour
    paths:
      - conda-bld/$BIM2SIM_NAME

.conda_build:main:
  variables:
    BIM2SIM_VERSION: ""
  extends: .conda_build

.conda_build:dev:
  extends: .conda_build
  variables:
    BIM2SIM_VERSION: "_dev"


.conda_build:plugin:dev:
  extends: .conda_build:dev
  rules:
    - if: $CI_COMMIT_BRANCH == "development"
      when: on_success
    - if: $CI_COMMIT_MESSAGE =~ /ci_build_dev/
      when: on_success
    - if: $CI_COMMIT_MESSAGE =~ /ci_build_plugin_dev/
      when: on_success

.conda_build:plugin:main:
  extends: .conda_build:main
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /ci_build_plugin_main/
      when: on_success
    - if: $CI_COMMIT_BRANCH == "main"
      when: on_success
    - if: $CI_COMMIT_MESSAGE =~ /ci_build_main/
      when: on_success

# [Build Conda Base]
conda_build_bim2sim:base:main:
    stage: build_conda_base
    variables:
        BIM2SIM_NAME: "bim2sim"
        CONDA_FILE:  "conda_recipe/basic_build/meta.yaml"
    extends: .conda_build:main
    rules:
      - if: $CI_COMMIT_BRANCH == "main"
        when: on_success
      - if: $CI_COMMIT_MESSAGE =~ /ci_build_main/
        when: on_success
      - if: $CI_COMMIT_MESSAGE =~ /ci_build_base_dev/
        when: on_success

conda_build_bim2sim:base:dev:
    stage: build_conda_base
    variables:
        BIM2SIM_NAME: "bim2sim"
        CONDA_FILE:  "conda_recipe/basic_build/meta.yaml"
    extends: .conda_build:dev
    rules:
      - if: $CI_COMMIT_MESSAGE =~ /ci_build_base_dev/
        when: on_success
      - if: $CI_COMMIT_BRANCH == "development"
        when: on_success
      - if: $CI_COMMIT_MESSAGE =~ /ci_build_dev/
        when: on_success


# [Build Conda Plugins]

build_conda_plugin:aixlib:main:
    stage: build_conda_plugin
    variables:
        BIM2SIM_NAME: "bim2sim_aixlib"
        CONDA_FILE: "conda_recipe/plugins/PluginAixLib/meta.yaml"
    extends: .conda_build:plugin:main

build_conda_plugin:aixlib:dev:
    stage: build_conda_plugin
    variables:
        BIM2SIM_NAME: "bim2sim_aixlib"
        CONDA_FILE: "conda_recipe/plugins/PluginAixLib/meta.yaml"
    extends: .conda_build:plugin:dev

build_conda_plugin:cfd:main:
    stage: build_conda_plugin
    variables:
        BIM2SIM_NAME: "bim2sim_cfd"
        CONDA_FILE: "conda_recipe/plugins/PluginCFD/meta.yaml"
    extends: .conda_build:plugin:main

build_conda_plugin:cfd:dev:
    stage: build_conda_plugin
    variables:
        BIM2SIM_NAME: "bim2sim_cfd"
        CONDA_FILE: "conda_recipe/plugins/PluginCFD/meta.yaml"
    extends: .conda_build:plugin:dev

build_conda_plugin:energyplus:main:
    stage: build_conda_plugin
    variables:
        BIM2SIM_NAME: "bim2sim_energyplus"
        CONDA_FILE: "conda_recipe/plugins/PluginEnergyPlus/meta.yaml"
    extends: .conda_build:plugin:main

build_conda_plugin:energyplus:dev:
    stage: build_conda_plugin
    variables:
        BIM2SIM_NAME: "bim2sim_energyplus"
        CONDA_FILE: "conda_recipe/plugins/PluginEnergyPlus/meta.yaml"
    extends: .conda_build:plugin:dev

build_conda_plugin:hkesim:main:
    stage: build_conda_plugin
    variables:
        BIM2SIM_NAME: "bim2sim_hkesim"
        CONDA_FILE: "conda_recipe/plugins/PluginHKESim/meta.yaml"
    extends: .conda_build:plugin:main

build_conda_plugin:hkesim:dev:
    stage: build_conda_plugin
    variables:
        BIM2SIM_NAME: "bim2sim_hkesim"
        CONDA_FILE: "conda_recipe/plugins/PluginHKESim/meta.yaml"
    extends: .conda_build:plugin:dev


build_conda_plugin:lca:main:
    stage: build_conda_plugin
    variables:
      BIM2SIM_NAME: "bim2sim_lca"
      CONDA_FILE: "conda_recipe/plugins/PluginLCA/meta.yaml"
    extends: .conda_build:plugin:main

build_conda_plugin:lca:dev:
    stage: build_conda_plugin
    variables:
      BIM2SIM_NAME: "bim2sim_lca"
      CONDA_FILE: "conda_recipe/plugins/PluginLCA/meta.yaml"
    extends: .conda_build:plugin:dev

build_conda_plugin:teaser:main:
    stage: build_conda_plugin
    variables:
        BIM2SIM_NAME: "bim2sim_teaser"
        CONDA_FILE: "conda_recipe/plugins/PluginTeaser/meta.yaml"
    extends: .conda_build:plugin:main

build_conda_plugin:teaser:dev:
    stage: build_conda_plugin
    variables:
        BIM2SIM_NAME: "bim2sim_teaser"
        CONDA_FILE: "conda_recipe/plugins/PluginTeaser/meta.yaml"
    extends: .conda_build:plugin:dev

# [Build Conda total]

build_conda_bim2sim:total:main:
    stage: build_conda_total
    variables:
        BIM2SIM_NAME: "bim2sim_total"
        CONDA_FILE: "conda_recipe/total/meta.yaml"
    extends: .conda_build:main
    rules:
      - if: $CI_COMMIT_MESSAGE =~ /ci_build_total_main/
        when: on_success
      - if: $CI_COMMIT_BRANCH == "main"
        when: on_success
      - if: $CI_COMMIT_MESSAGE =~ /ci_build_main/
        when: on_success


build_conda_bim2sim:total:dev:
    stage: build_conda_total
    variables:
        BIM2SIM_NAME: "bim2sim_total"
        CONDA_FILE: "conda_recipe/total/meta.yaml"
    extends: .conda_build:dev
    rules:
      - if: $CI_COMMIT_MESSAGE =~ /ci_build_total_dev/
        when: on_success
      - if: $CI_COMMIT_BRANCH == "development"
        when: on_success
      - if: $CI_COMMIT_MESSAGE =~ /ci_build_dev/
        when: on_success



.conda_release:
  image: continuumio/miniconda3
  script:
    - apt update
    - apt install libgl1 -y
    - conda install conda-build git conda-verify -y
    - conda install anaconda -y
    - conda update --all  -y
    - conda install conda-build anaconda-client -y
    - anaconda logout
    - anaconda login --username bim2sim --password $CONDA_TOKEN --hostname $CI_JOB_ID
    - conda convert -p osx-64 conda-bld/$BIM2SIM_NAME/linux-64/$BIM2SIM_NAME-* --output-dir conda-bld/$BIM2SIM_NAME -f
    - conda convert -p osx-arm64 conda-bld/$BIM2SIM_NAME/linux-64/$BIM2SIM_NAME-* --output-dir conda-bld/$BIM2SIM_NAME -f
    - conda convert -p win-64 conda-bld/$BIM2SIM_NAME/linux-64/$BIM2SIM_NAME-* --output-dir conda-bld/$BIM2SIM_NAME -f
    - anaconda upload conda-bld/$BIM2SIM_NAME/linux-64/$BIM2SIM_NAME-* --force
    - anaconda upload conda-bld/$BIM2SIM_NAME/osx-64/$BIM2SIM_NAME-* --force
    - anaconda upload conda-bld/$BIM2SIM_NAME/win-64/$BIM2SIM_NAME-* --force
    - anaconda logout
  retry:
    max: 2
    when: runner_system_failure
  artifacts:
    expire_in: 1 hour
    paths:
      - conda-bld/$BIM2SIM_NAME




.conda_release:plugin:dev:
  extends: .conda_release
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /ci_build_plugin_dev/
      when: manual
    - if: $CI_COMMIT_BRANCH == "development"
      when: on_success
    - if: $CI_COMMIT_MESSAGE =~ /ci_build_dev/
      when: manual

.conda_release:plugin:main:
  extends: .conda_release
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: on_success
    - if: $CI_COMMIT_MESSAGE =~ /ci_build_main/
      when: manual
    - if: $CI_COMMIT_MESSAGE =~ /ci_build_plugin_main/
      when: manual

# [release base conda image]
release_conda_bim2sim:base:main:
  stage: release_conda_base
  variables:
    BIM2SIM_NAME: "bim2sim"
  dependencies:
    - conda_build_bim2sim:base:main
  extends: .conda_release
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /ci_build_base_main/
      when: manual
    - if: $CI_COMMIT_BRANCH == "main"
      when: on_success
    - if: $CI_COMMIT_MESSAGE =~ /ci_build_main/
      when: manual


release_conda_bim2sim:base:dev:
  stage: release_conda_base
  variables:
    BIM2SIM_NAME: "bim2sim"
  dependencies:
    - conda_build_bim2sim:base:dev
  extends: .conda_release
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /ci_build_base_dev/
      when: manual
    - if: $CI_COMMIT_BRANCH == "development"
      when: on_success
    - if: $CI_COMMIT_MESSAGE =~ /ci_build_dev/
      when: manual

# [release plugin conda image]

release_conda_plugin:aixlib:main:
  stage: release_conda_plugin
  variables:
    BIM2SIM_NAME: "bim2sim_aixlib"
  dependencies:
    - build_conda_plugin:aixlib:main
  extends: .conda_release:plugin:main

release_conda_plugin:aixlib:dev:
  stage: release_conda_plugin
  variables:
    BIM2SIM_NAME: "bim2sim_aixlib"
  dependencies:
    - build_conda_plugin:aixlib:dev
  extends: .conda_release:plugin:dev


release_conda_plugin:cfd:main:
  stage: release_conda_plugin
  variables:
    BIM2SIM_NAME: "bim2sim_cfd"
  dependencies:
    - build_conda_plugin:cfd:main
  extends: .conda_release:plugin:main

release_conda_plugin:cfd:dev:
  stage: release_conda_plugin
  variables:
    BIM2SIM_NAME: "bim2sim_cfd"
  dependencies:
    - build_conda_plugin:cfd:dev
  extends: .conda_release:plugin:dev

release_conda_plugin:energyplus:main:
  stage: release_conda_plugin
  variables:
    BIM2SIM_NAME: "bim2sim_energyplus"
  dependencies:
    - build_conda_plugin:energyplus:main
  extends: .conda_release:plugin:main

release_conda_plugin:energyplus:dev:
  stage: release_conda_plugin
  variables:
    BIM2SIM_NAME: "bim2sim_energyplus"
  dependencies:
    - build_conda_plugin:energyplus:dev
  extends: .conda_release:plugin:dev

release_conda_plugin:hkesim:main:
  stage: release_conda_plugin
  variables:
    BIM2SIM_NAME: "bim2sim_hkesim"
  dependencies:
    - build_conda_plugin:hkesim:main
  extends: .conda_release:plugin:main


release_conda_plugin:hkesim:dev:
  stage: release_conda_plugin
  variables:
    BIM2SIM_NAME: "bim2sim_hkesim"
  dependencies:
    - build_conda_plugin:hkesim:dev
  extends: .conda_release:plugin:dev

release_conda_plugin:lca:main:
  stage: release_conda_plugin
  variables:
    BIM2SIM_NAME: "bim2sim_lca"
  dependencies:
    - build_conda_plugin:lca:main
  extends: .conda_release:plugin:main

release_conda_plugin:lca:dev:
  stage: release_conda_plugin
  variables:
    BIM2SIM_NAME: "bim2sim_lca"
  dependencies:
    - build_conda_plugin:lca:dev
  extends: .conda_release:plugin:dev


release_conda_plugin:teaser:main:
  stage: release_conda_plugin
  variables:
    BIM2SIM_NAME: "bim2sim_teaser"
  dependencies:
    - build_conda_plugin:teaser:main
  extends: .conda_release:plugin:main

release_conda_plugin:teaser:dev:
  stage: release_conda_plugin
  variables:
    BIM2SIM_NAME: "bim2sim_teaser"
  dependencies:
    - build_conda_plugin:teaser:dev
  extends: .conda_release:plugin:dev

release_conda_bim2sim:total:main:
  stage: release_conda_total
  variables:
    BIM2SIM_NAME: "bim2sim_total"
  dependencies:
    - build_conda_bim2sim:total:main
  extends: .conda_release
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /ci_build_total_main/
      when: manual
    - if: $CI_COMMIT_BRANCH == "main"
      when: on_success
    - if: $CI_COMMIT_MESSAGE =~ /ci_build_main/
      when: manual


# [conda total]

release_conda_bim2sim:total:dev:
  stage: release_conda_total
  variables:
    BIM2SIM_NAME: "bim2sim_total"
  dependencies:
    - build_conda_bim2sim:total:dev
  extends: .conda_release
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /ci_build_total_dev/
      when: manual
    - if: $CI_COMMIT_BRANCH == "development"
      when: on_success
    - if: $CI_COMMIT_MESSAGE =~ /ci_build_dev/
      when: manual
