# DISCLAIMER: Viewer has been generated by GPT5. Not all functions may work
# as expected, but this viewer helps to load and display space boundaries
# from IFC (incl. a setup from scratch).


import sys
from typing import List, Tuple, Optional

import ifcopenshell
import ifcopenshell.geom

from OCC.Core.TopoDS import TopoDS_Shape
from OCC.Core.gp import gp_Trsf
from OCC.Core.BRepBuilderAPI import BRepBuilderAPI_Transform

# Optional: viewer for quick inspection (uses pythonocc)
from OCC.Display.SimpleGui import init_display
from OCC.Core.ShapeFix import ShapeFix_Shape, ShapeFix_Face, ShapeFix_Wire
from OCC.Core.ShapeAnalysis import ShapeAnalysis_FreeBounds
from OCC.Core.TopExp import TopExp_Explorer
from OCC.Core.TopAbs import TopAbs_FACE, TopAbs_WIRE, TopAbs_VERTEX
from OCC.Core.TopoDS import topods_Face, topods_Wire, topods_Vertex, TopoDS_Compound
from OCC.Core.BRep import BRep_Builder
from OCC.Core.BRep import BRep_Tool
from OCC.Core.BRepBuilderAPI import BRepBuilderAPI_MakeFace
from OCC.Core.gp import gp_Vec
from OCC.Core.Geom import Geom_Plane
from OCC.Core.ShapeFix import ShapeFix_ShapeTolerance
from OCC.Core.BRepCheck import BRepCheck_Analyzer
from OCC.Core.TopAbs import TopAbs_EDGE


def heal_boundary_shape(shape: TopoDS_Shape) -> TopoDS_Shape:
    # Global shape fix and tolerance normalization
    try:
        sfix = ShapeFix_Shape(shape)
        sfix.Perform()
        shape = sfix.Shape()
    except Exception:
        pass
    try:
        stol = ShapeFix_ShapeTolerance()
        stol.SetMinTolerance(shape, 1e-7)
        stol.SetMaxTolerance(shape, 1e-3)
        stol.SetTolerance(shape, 1e-5)
    except Exception:
        pass
    try:
        BRepLib.BuildCurves3d(shape)
        BRepLib.SameParameter(shape, 1e-7)
    except Exception:
        pass

    faces = []

    # Pass 1: fix any existing faces
    try:
        exp_face = TopExp_Explorer(shape, TopAbs_FACE)
        while exp_face.More():
            face = topods_Face(exp_face.Current())
            try:
                sff = ShapeFix_Face(face)
                sff.SetPrecision(1e-7)
                sff.SetMaxTolerance(1e-3)
                sff.FixOrientation()
                sff.FixWires()
                try:
                    wtool = sff.FixWireTool()
                    wtool.SetPrecision(1e-7)
                    wtool.SetMinTolerance(1e-7)
                    wtool.SetMaxTolerance(1e-3)
                except Exception:
                    pass
                sff.Perform()
                face = sff.Face()
            except Exception:
                pass
            if not face.IsNull():
                faces.append(face)
            exp_face.Next()
    except Exception:
        pass

    # Helper: infer a plane from 3 non-collinear points
    def _infer_plane_from_points(pts):
        for i in range(len(pts)):
            for j in range(i + 1, len(pts)):
                for k in range(j + 1, len(pts)):
                    v1 = gp_Vec(pts[i], pts[j])
                    v2 = gp_Vec(pts[i], pts[k])
                    if v1.Crossed(v2).Magnitude() > 1e-12:
                        return Geom_Plane(pts[i], pts[j], pts[k]).Pln()
        return None

    # Helper: ordered vertices from a wire (after wire fix)
    def _ordered_points_from_wire(wire, tol=1e-7):
        pts = []
        try:
            # Explore edges in wire order
            wx = BRepTools_WireExplorer(wire)
            prev_pt = None
            first = True
            while wx.More():
                e = wx.Current()
                # Get end vertices
                v1 = TopExp.FirstVertex(e)
                v2 = TopExp.LastVertex(e)
                p1 = BRep_Tool.Pnt(v1)
                p2 = BRep_Tool.Pnt(v2)

                def _dist(a, b):
                    return gp_Vec(a, b).Magnitude()

                if first:
                    pts.append(p1)
                    pts.append(p2)
                    prev_pt = pts[-1]
                    first = False
                else:
                    # Append the vertex that continues the chain
                    if _dist(prev_pt, p1) <= tol:
                        pts.append(p2)
                        prev_pt = p2
                    elif _dist(prev_pt, p2) <= tol:
                        pts.append(p1)
                        prev_pt = p1
                    else:
                        # If neither matches (edge orientation issue), append both to keep continuity
                        # This is rare after FixReorder; still handle gracefully
                        pts.append(p1)
                        pts.append(p2)
                        prev_pt = p2
                wx.Next()

            # Remove consecutive duplicates
            cleaned = []
            for p in pts:
                if not cleaned or gp_Vec(cleaned[-1], p).Magnitude() > tol:
                    cleaned.append(p)
            # Ensure closed
            if cleaned and gp_Vec(cleaned[0], cleaned[-1]).Magnitude() > tol:
                cleaned.append(cleaned[0])
            return cleaned
        except Exception:
            return pts

    # 2D geometry helpers on a plane
    def _pts3d_to_uv(plane, pts3d):
        uvs = []
        for p in pts3d:
            try:
                u, v = ElSLib.Parameters(plane, p)
            except Exception:
                # Fallback if Parameters fails (rare): project using plane axes
                ax = plane.Position()
                vec = gp_Vec(ax.Location(), p)
                ux = gp_Vec(ax.XDirection().XYZ())
                uy = gp_Vec(ax.YDirection().XYZ())
                u = vec.Dot(ux)
                v = vec.Dot(uy)
            uvs.append((float(u), float(v)))
        return uvs

    def _uv_to_pts3d(plane, uvs):
        pts = []
        for u, v in uvs:
            pts.append(ElSLib.Value(u, v, plane))
        return pts

    # Segment intersection in 2D
    def _ccw(a, b, c):
        return (c[1] - a[1]) * (b[0] - a[0]) > (b[1] - a[1]) * (c[0] - a[0])

    def _seg_intersect(a, b, c, d):
        # Proper intersection (exclude touching endpoints)
        return _ccw(a, c, d) != _ccw(b, c, d) and _ccw(a, b, c) != _ccw(a, b, d)

    # 2-opt reordering to remove crossings
    def _two_opt_simple_polygon(uvs, max_iters=50):
        if len(uvs) < 4:
            return uvs
        # Work on open list (last equals first), ignore duplicate last
        closed = gp_Vec(gp_Pnt(uvs[0][0], uvs[0][1], 0), gp_Pnt(uvs[-1][0], uvs[-1][1], 0)).Magnitude() < 1e-12
        pts = uvs[:-1] if closed else list(uvs)
        n = len(pts)

        def _area(poly):
            a = 0.0
            for i in range(n):
                x1, y1 = poly[i]
                x2, y2 = poly[(i + 1) % n]
                a += x1 * y2 - x2 * y1
            return a * 0.5

        # Ensure CCW orientation (optional)
        if _area(pts) < 0:
            pts.reverse()

        changed = True
        it = 0
        while changed and it < max_iters:
            changed = False
            it += 1
            for i in range(n - 1):
                a1 = pts[i]
                a2 = pts[(i + 1) % n]
                for j in range(i + 2, n - (0 if i > 0 else 1)):
                    b1 = pts[j]
                    b2 = pts[(j + 1) % n]
                    if _seg_intersect(a1, a2, b1, b2):
                        # Reverse the sub-chain to remove intersection
                        pts[i + 1:j + 1] = reversed(pts[i + 1:j + 1])
                        changed = True
                        break
                if changed:
                    break

        # Close loop
        pts.append(pts[0])
        return pts

    # Build a face from a wire, with polygon fallback
    def _build_face_from_wire(wire: TopoDS_Shape):
        # First: aggressive wire fix
        try:
            try:
                wfix = ShapeFix_Wire(topods_Wire(wire))
            except Exception:
                wfix = ShapeFix_Wire(wire)
            wfix.SetPrecision(1e-7)
            wfix.SetMinTolerance(1e-7)
            wfix.SetMaxTolerance(1e-3)
            try:
                wfix.SetClosed(True)
            except Exception:
                pass
            wfix.FixReorder()
            wfix.FixConnected()
            wfix.FixSmall(Precision.Confusion())
            wfix.FixDegenerated()
            wfix.FixSelfIntersection()
            wfix.FixLacking()
            wfix.Perform()
            wire = wfix.Wire()
        except Exception:
            pass

        # Try direct face creation
        try:
            mf = BRepBuilderAPI_MakeFace(wire, True)
            f = mf.Face()
            if not f.IsNull() and BRepCheck_Analyzer(f).IsValid():
                sff = ShapeFix_Face(f)
                sff.SetPrecision(1e-7)
                sff.SetMaxTolerance(1e-3)
                sff.Perform()
                return sff.Face()
        except Exception:
            pass

        # Polygon fallback: reorder vertices to remove crossings and rebuild planar wire
        # Gather ordered points and infer plane
        try:
            pts3d = _ordered_points_from_wire(wire, tol=1e-6)
            if len(pts3d) >= 3:
                plane = _infer_plane_from_points(pts3d)
                if plane:
                    uvs = _pts3d_to_uv(plane, pts3d)
                    uvs = _two_opt_simple_polygon(uvs, max_iters=80)
                    pts3d_clean = _uv_to_pts3d(plane, uvs)

                    # Rebuild wire from straight segments on the plane
                    try:
                        mw = BRepBuilderAPI_MakeWire()
                        for i in range(len(pts3d_clean) - 1):
                            e = BRepBuilderAPI_MakeEdge(pts3d_clean[i], pts3d_clean[i + 1]).Edge()
                            mw.Add(e)
                        if mw.IsDone():
                            w2 = mw.Wire()
                            # Heal new wire and create face
                            try:
                                wfix2 = ShapeFix_Wire(w2)
                                wfix2.SetPrecision(1e-7)
                                wfix2.SetMinTolerance(1e-7)
                                wfix2.SetMaxTolerance(1e-3)
                                try:
                                    wfix2.SetClosed(True)
                                except Exception:
                                    pass
                                wfix2.FixReorder()
                                wfix2.FixConnected()
                                wfix2.FixSmall(Precision.Confusion())
                                wfix2.FixDegenerated()
                                wfix2.Perform()
                                w2 = wfix2.Wire()
                            except Exception:
                                pass

                            # Try direct face; if still problematic, force plane context
                            try:
                                mf2 = BRepBuilderAPI_MakeFace(w2, True)
                                f2 = mf2.Face()
                                if not f2.IsNull() and BRepCheck_Analyzer(f2).IsValid():
                                    sff2 = ShapeFix_Face(f2)
                                    sff2.SetPrecision(1e-7)
                                    sff2.SetMaxTolerance(1e-3)
                                    sff2.Perform()
                                    return sff2.Face()
                            except Exception:
                                pass

                            try:
                                mf3 = BRepBuilderAPI_MakeFace(plane, w2, True)
                                f3 = mf3.Face()
                                if not f3.IsNull():
                                    sff3 = ShapeFix_Face(f3)
                                    sff3.SetPrecision(1e-7)
                                    sff3.SetMaxTolerance(1e-3)
                                    sff3.Perform()
                                    return sff3.Face()
                            except Exception:
                                pass
                    except Exception:
                        pass
        except Exception:
            pass

        # Plane fallback from original wire if all else fails
        try:
            pts = []
            expV = TopExp_Explorer(wire, TopAbs_VERTEX)
            while expV.More():
                v = topods_Vertex(expV.Current())
                pts.append(BRep_Tool.Pnt(v))
                expV.Next()
            plane = _infer_plane_from_points(pts)
            if plane:
                mf = BRepBuilderAPI_MakeFace(plane, topods_Wire(wire), True)
                f = mf.Face()
                if not f.IsNull():
                    sff = ShapeFix_Face(f)
                    sff.SetPrecision(1e-7)
                    sff.SetMaxTolerance(1e-3)
                    sff.Perform()
                    return sff.Face()
        except Exception:
            pass

        return None

    # Pass 2: if no faces, build from closed wires with polygon fallback
    if not faces:
        try:
            fb = ShapeAnalysis_FreeBounds(shape, 1e-6, False, False)
            closed = fb.GetClosedWires()
            exp_wire = TopExp_Explorer(closed, TopAbs_WIRE)
            while exp_wire.More():
                wire = topods_Wire(exp_wire.Current())
                f = _build_face_from_wire(wire)
                if f and not f.IsNull():
                    faces.append(f)
                exp_wire.Next()
        except Exception:
            pass

    # Assemble faces into a compound
    if faces:
        builder = BRep_Builder()
        comp = TopoDS_Compound()
        builder.MakeCompound(comp)
        for f in faces:
            try:
                builder.Add(comp, f)
            except Exception:
                continue
        try:
            BRepLib.SameParameter(comp, 1e-7)
        except Exception:
            pass
        return comp

    # Fallback
    return shape

def display_occ_shapes(ifc, shapes):
    """Display TopoDS_Shapes of space boundaries"""
    display, start_display, add_menu, add_function_to_menu = init_display()
    all_relbuild_elems = []
    for guid, shape in shapes:
        bound = ifc.by_guid(guid)
        relbuildelem = bound.RelatedBuildingElement
        # 'blue', 'red', 'magenta', 'yellow', 'green', 'white', 'cyan'
        if relbuildelem:
            if relbuildelem.is_a('IfcWall'):
                color = 'blue'
            elif relbuildelem.is_a('IfcSlab'):
                color = 'red'
            elif relbuildelem.is_a('IfcBuildingElementProxy'):
                color = 'yellow'
            elif relbuildelem.is_a('IfcDoor'):
                color = 'green'
            elif relbuildelem.is_a('IfcWindow'):
                color = 'green'
            elif relbuildelem.is_a('IfcCurtainWall'):
                color = 'cyan'
            elif relbuildelem.is_a('IfcCovering'):
                color = 'orange'
            elif relbuildelem.is_a('IfcColumn'):
                color = 'black'
            elif relbuildelem.is_a('IfcBuildingElementProxy'):
                color = 'red'
            else:
                color = 'darkblue'
                print(relbuildelem.is_a())
            all_relbuild_elems.append(relbuildelem.is_a())
        else:
            color = 'white'
        try:
            display.DisplayShape(shape, color=color)
        except Exception:
            continue
    print(set(all_relbuild_elems))
    display.FitAll()
    start_display()


# --- Placement utilities (IfcLocalPlacement -> gp_Trsf) ---

def _to_float_list(seq):
    return [float(x) for x in seq]


def _norm3(v):
    x, y, z = v
    n = (x*x + y*y + z*z) ** 0.5
    return (x / n, y / n, z / n) if n else (0.0, 0.0, 1.0)


def _cross(a, b):
    ax, ay, az = a
    bx, by, bz = b
    return (ay*bz - az*by, az*bx - ax*bz, ax*by - ay*bx)


def _axis2placement_to_basis(a2p):
    # Returns orthonormal basis (X, Y, Z) and origin (px, py, pz)
    loc = a2p.Location
    coords = list(loc.Coordinates)
    px = float(coords[0]) if len(coords) > 0 else 0.0
    py = float(coords[1]) if len(coords) > 1 else 0.0
    pz = float(coords[2]) if len(coords) > 2 else 0.0

    if a2p.is_a("IfcAxis2Placement3D"):
        zdir = (0.0, 0.0, 1.0)
        xdir = (1.0, 0.0, 0.0)
        if getattr(a2p, "Axis", None):
            zvals = _to_float_list(a2p.Axis.DirectionRatios)
            zdir = _norm3((zvals + [0.0, 0.0, 0.0])[:3])
        if getattr(a2p, "RefDirection", None):
            xvals = _to_float_list(a2p.RefDirection.DirectionRatios)
            xdir = _norm3((xvals + [0.0, 0.0, 0.0])[:3])
        ydir = _cross(zdir, xdir)
        xdir = _cross(ydir, zdir)
        xdir = _norm3(xdir)
        ydir = _norm3(ydir)
        zdir = _norm3(zdir)
        return xdir, ydir, zdir, (px, py, pz)

    if a2p.is_a("IfcAxis2Placement2D"):
        # 2D placement in XY plane
        xdir = (1.0, 0.0, 0.0)
        if getattr(a2p, "RefDirection", None):
            xvals = _to_float_list(a2p.RefDirection.DirectionRatios)
            # Promote 2D to 3D by adding 0 z
            xdir = _norm3(((xvals + [0.0])[:2]) + [0.0])
        zdir = (0.0, 0.0, 1.0)
        ydir = _cross(zdir, xdir)
        xdir = _cross(ydir, zdir)
        xdir = _norm3(xdir)
        ydir = _norm3(ydir)
        return xdir, ydir, zdir, (px, py, pz)

    # Fallback identity basis at given location
    return (1.0, 0.0, 0.0), (0.0, 1.0, 0.0), (0.0, 0.0, 1.0), (px, py, pz)


def _mat_mul(a, b):
    r = [[0.0]*4 for _ in range(4)]
    for i in range(4):
        for j in range(4):
            r[i][j] = sum(a[i][k] * b[k][j] for k in range(4))
    return r


def _basis_to_matrix(xdir, ydir, zdir, pos):
    (xx, xy, xz) = xdir
    (yx, yy, yz) = ydir
    (zx, zy, zz) = zdir
    (tx, ty, tz) = pos
    return [
        [xx, yx, zx, tx],
        [xy, yy, zy, ty],
        [xz, yz, zz, tz],
        [0.0, 0.0, 0.0, 1.0],
    ]


def _local_placement_to_matrix(lpl):
    if lpl is None:
        return [
            [1.0, 0.0, 0.0, 0.0],
            [0.0, 1.0, 0.0, 0.0],
            [0.0, 0.0, 1.0, 0.0],
            [0.0, 0.0, 0.0, 1.0],
        ]
    parent_m = _local_placement_to_matrix(getattr(lpl, "PlacementRelTo", None))
    xdir, ydir, zdir, pos = _axis2placement_to_basis(lpl.RelativePlacement)
    local_m = _basis_to_matrix(xdir, ydir, zdir, pos)
    return _mat_mul(parent_m, local_m)


def _matrix_to_trsf(m):
    t = gp_Trsf()
    t.SetValues(
        m[0][0], m[0][1], m[0][2], m[0][3],
        m[1][0], m[1][1], m[1][2], m[1][3],
        m[2][0], m[2][1], m[2][2], m[2][3]
    )
    return t


def _product_world_trsf(prod) -> gp_Trsf:
    if prod is None:
        return gp_Trsf()
    lpl = getattr(prod, "ObjectPlacement", None)
    m = _local_placement_to_matrix(lpl)
    return _matrix_to_trsf(m)


# --- Boundary item selection and shape building ---

def _pick_connection_item_and_product(rb) -> Tuple[Optional[object], Optional[object]]:
    cg = getattr(rb, "ConnectionGeometry", None)
    if cg is None:
        return None, None

    # Prefer geometry on the space side (RelatingSpace). Fallback to RelatedBuildingElement.
    if cg.is_a("IfcConnectionSurfaceGeometry"):
        if getattr(cg, "SurfaceOnRelatingElement", None):
            return cg.SurfaceOnRelatingElement, rb.RelatingSpace
        elif getattr(cg, "SurfaceOnRelatedElement", None):
            return cg.SurfaceOnRelatedElement, getattr(rb, "RelatedBuildingElement", None)

    if cg.is_a("IfcConnectionCurveGeometry"):
        if getattr(cg, "CurveOnRelatingElement", None):
            return cg.CurveOnRelatingElement, rb.RelatingSpace
        elif getattr(cg, "CurveOnRelatedElement", None):
            return cg.CurveOnRelatedElement, getattr(rb, "RelatedBuildingElement", None)

    return None, None


def build_space_boundary_shapes(ifc):
    """Create TopoDS_Shapes for IfcRelSpaceBoundary connection geometry, transformed to world."""
    gs = ifcopenshell.geom.settings()
    # Ensure OCC shapes and curves are included (for curve-based boundaries)
    gs.set(gs.USE_PYTHON_OPENCASCADE, True)
    gs.set(gs.USE_WORLD_COORDS, True)
    gs.set(
        "dimensionality",
        ifcopenshell.ifcopenshell_wrapper.CURVES_SURFACES_AND_SOLIDS)  # 2
    shapes = []

    # Collect all boundary subtypes
    boundaries = []
    for t in ("IfcRelSpaceBoundary2ndLevel", "IfcRelSpaceBoundary1stLevel",
              "IfcRelSpaceBoundary"):
        try:
            boundaries.extend(ifc.by_type(t))
        except Exception:
            pass

    for rb in boundaries:
        item, prod = _pick_connection_item_and_product(rb)
        if not item:
            continue
        try:
            shape_data = ifcopenshell.geom.create_shape(gs, item)
        except Exception as ex:
            print(f"Exception {ex} for {rb}!")
            continue
        occ_shape = shape_data  # TopoDS_Shape
        tr = _product_world_trsf(prod)
        tr_shape = BRepBuilderAPI_Transform(occ_shape, tr, True).Shape()
        tr_shape = heal_boundary_shape(tr_shape)  # <-- shape healing
        shapes.append([rb.GlobalId, tr_shape])

    return shapes


def main():
    # Choose file path from CLI or dialog

    path = "path/to/ifc/file"

    try:
        ifc = ifcopenshell.open(path)
    except Exception as e:
        print(f"Failed to open IFC: {e}")
        return

    shapes = build_space_boundary_shapes(ifc)
    print(f"Built {len(shapes)} space boundary shapes.")

    # Optional quick display
    if shapes:
        display_occ_shapes(ifc, shapes)
    else:
        print("No drawable connection geometry found for space boundaries.")


if __name__ == "__main__":
    main()