name: bim2sim_dev_env

channels:
  - dsdale24
  - inso
  - conda-forge
  - anaconda
dependencies:
  - bim2sim_aixlib==*.dev
  - bim2sim_cfd==*.dev
  - bim2sim_energyplus==*.dev
  - bim2sim_hkesim==*.dev
  - bim2sim_lca==*.dev
  - bim2sim_tease==*.dev
  
  - pip:
    - deep_translator
    - string_grouper
    - scipy==1.8.0
    - geomeppy>=0.11.8
    - eppy
    - https://github.com/tpaviot/pythonocc-utils/archive/refs/heads/master.zip
    - git+https://github.com/squidKid-deluxe/pyvis.git@fix-show
    - git+https://github.com/RWTH-EBC/TEASER@development
    - git+https://github.com/DaJansenGit/BuildingsPy.git
    