name: bim2sim_env

channels:
  - dsdale24
  - inso
  - conda-forge
  - anaconda

dependencies:
  - python>=3.8.*,<3.10.*
  - setuptools
  - numpy
  - cython
  - pip
  - pythonocc-core<=7.5.1
  - ifcopenshell
  - occt<=7.5.1
  - pandas
  - matplotlib
  - networkx>=2.2
  - python-dateutil
  - mako
  - pint
  - certifi
  - beautifulsoup4 >=4.9.3
  - pip:
    - deep-translator
    - string_grouper
    - https://github.com/tpaviot/pythonocc-utils/archive/refs/heads/master.zip

