{% set data = load_setup_py_data(setup_file='../../bim2sim/plugins/setup.py', from_recipe_dir=True) %}

package:
  name: {{BIM2SIM_NAME}}
  version: {{data.get('version')}}{{BIM2SIM_FLAG}}

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: '0'
  entry_points:
    - bim2sim = bim2sim.__main__:commandline_interface
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python>=3.8,<3.10
    - pip
    - setuptools
  run:
    - python >=3.8,<3.10
    - bim2sim_aixlib=={{BIM2SIM_BASE_VERSION}}{{BIM2SIM_FLAG}}
    - bim2sim_cfd=={{BIM2SIM_BASE_VERSION}}{{BIM2SIM_FLAG}}
    - bim2sim_energyplus=={{BIM2SIM_BASE_VERSION}}{{BIM2SIM_FLAG}}
    - bim2sim_hkesim=={{BIM2SIM_BASE_VERSION}}{{BIM2SIM_FLAG}}
    - bim2sim_lca=={{BIM2SIM_BASE_VERSION}}{{BIM2SIM_FLAG}}
    - bim2sim_teaser=={{BIM2SIM_BASE_VERSION}}{{BIM2SIM_FLAG}}

test:
  imports:
    - bim2sim
    # bim2sim.plugins.PluginAixLib
    # bim2sim.plugins.PluginTEASER
    # bim2sim.plugins.PluginCFD
    # bim2sim.plugins.PluginEnergyPlus
    # bim2sim.plugins.PluginLCA
  requires:
    - python  >=3.8,<3.10
    - bim2sim_aixlib=={{BIM2SIM_BASE_VERSION}}{{BIM2SIM_FLAG}}
    - bim2sim_cfd=={{BIM2SIM_BASE_VERSION}}{{BIM2SIM_FLAG}}
    - bim2sim_energyplus=={{BIM2SIM_BASE_VERSION}}{{BIM2SIM_FLAG}}
    - bim2sim_hkesim=={{BIM2SIM_BASE_VERSION}}{{BIM2SIM_FLAG}}
    - bim2sim_lca=={{BIM2SIM_BASE_VERSION}}{{BIM2SIM_FLAG}}
    - bim2sim_teaser=={{BIM2SIM_BASE_VERSION}}{{BIM2SIM_FLAG}}

  commands:
    - bim2sim -h
    - bim2sim --version
    - bash conda_recipe/plugins/PluginTeaser/test_teaser.sh # [not win]
    - bash conda_recipe/plugins/PluginAixLib/test_aixlib.sh  # [not win]
    - bash conda_recipe/plugins/PluginCFD/test_cfd.sh # [not win]
    - bash conda_recipe/plugins/PluginEnergyPlus/test_energyplus.sh # [not win]
    - bash conda_recipe/plugins/PluginLCA/test_lca.sh # [not win]
    - bash conda_recipe/plugins/PluginTeaser/test_teaser.sh # [not win]

  source_files:
    - conda_recipe/plugins/PluginTeaser/test_teaser.sh # [not win]
    - conda_recipe/plugins/PluginAixLib/test_aixlib.sh  # [not win]
    - conda_recipe/plugins/PluginCFD/test_cfd.sh # [not win]
    - conda_recipe/plugins/PluginEnergyPlus/test_energyplus.sh # [not win]
    - conda_recipe/plugins/PluginLCA/test_lca.sh # [not win]
    - conda_recipe/plugins/PluginTeaser/test_teaser.sh # [not win]
    - bim2sim
    - test
    - requirements.txt
    - dependency_requirements.txt
    # bim2sim/plugins/PluginAixLib/requirements.txt
    # bim2sim/plugins/PluginAixLib/dependency_requirements.txt
    # bim2sim/plugins/PluginEnergyPlus/requirements.txt
    # bim2sim/plugins/PluginEnergyPlus/dependency_requirements.txt
    # bim2sim/plugins/PluginCFD/requirements.txt
    # bim2sim/plugins/PluginCFD/dependency_requirements.txt
    # bim2sim/plugins/PluginHKESim/requirements.txt
    # bim2sim/plugins/PluginHKESim/dependency_requirements.txt
    # bim2sim/plugins/PluginLCA/requirements.txt
    # bim2sim/plugins/PluginLCA/dependency_requirements.txt
    # bim2sim/plugins/PluginTeaser/requirements.txt
    # bim2sim/plugins/PluginTeaser/dependency_requirements.txt

about:
  home: https://github.com/BIM2SIM/bim2sim
  summary: "A python tool to create simulation models for different domains based on BIM IFC models."
  description: "A python tool to create simulation models for different domains based on BIM IFC models. For documentation please visit https://ebc.pages.rwth-aachen.de/EBC_all/github_ci/bim2sim/development/docs/overview.html"
  license: LICENSE
