{% set data = load_setup_py_data(setup_file='../../bim2sim/plugins/setup.py', from_recipe_dir=True) %}

package:
  name: {{BIM2SIM_NAME}}
  version: {{data.get('version')}}{{BIM2SIM_FLAG}}

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: '0'
  entry_points:
    - bim2sim = bim2sim.__main__:commandline_interface
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python>=3.8.*,<3.10.*
    - pip 22.2.2
    - setuptools 65.5.0
  run:
    - python >=3.8.*,<3.10.*
    - bim2sim_aixlib=={{data.get('version')}}{{BIM2SIM_FLAG}}
    - bim2sim_cfd=={{data.get('version')}}{{BIM2SIM_FLAG}}
    - bim2sim_energyplus=={{data.get('version')}}{{BIM2SIM_FLAG}}
    - bim2sim_hkesim=={{data.get('version')}}{{BIM2SIM_FLAG}}
    - bim2sim_lca=={{data.get('version')}}{{BIM2SIM_FLAG}}
    - bim2sim_teaser=={{data.get('version')}}{{BIM2SIM_FLAG}}

test:
  imports:
    - bim2sim
    # bim2sim.plugins.PluginAixLib
    # bim2sim.plugins.PluginTEASER
    # bim2sim.plugins.PluginCFD
    # bim2sim.plugins.PluginEnergyPlus
    # bim2sim.plugins.PluginLCA
  requires:
    - python  >=3.8.*,<3.10.*
    - pint==0.20.1
    - pythonocc-core==7.6.2
    - ifcopenshell
    - bim2sim_aixlib=={{data.get('version')}}{{BIM2SIM_FLAG}}
    - bim2sim_cfd=={{data.get('version')}}{{BIM2SIM_FLAG}}
    - bim2sim_energyplus=={{data.get('version')}}{{BIM2SIM_FLAG}}
    - bim2sim_hkesim=={{data.get('version')}}{{BIM2SIM_FLAG}}
    - bim2sim_lca=={{data.get('version')}}{{BIM2SIM_FLAG}}
    - bim2sim_teaser=={{data.get('version')}}{{BIM2SIM_FLAG}}
  commands:
    - bim2sim -h
    - bim2sim --version
    - sh conda_recipe/plugins/PluginTeaser/test_teaser.sh # [not win]
    - sh conda_recipe/plugins/PluginAixLib/test_aixlib.sh  # [not win]
    - sh conda_recipe/plugins/PluginCFD/test_cfd.sh # [not win]
    - sh conda_recipe/plugins/PluginEnergyPlus/test_energyplus.sh # [not win]
    - sh conda_recipe/plugins/PluginLCA/test_lca.sh # [not win]
    - sh conda_recipe/plugins/PluginTeaser/test_teaser.sh # [not win]
    - coverage report -i  # [not win]
    - coverage html -i # [not win]

  source_files:
    - conda_recipe/plugins/PluginTeaser/test_teaser.sh # [not win]
    - conda_recipe/plugins/PluginAixLib/test_aixlib.sh  # [not win]
    - conda_recipe/plugins/PluginCFD/test_cfd.sh # [not win]
    - conda_recipe/plugins/PluginEnergyPlus/test_energyplus.sh # [not win]
    - conda_recipe/plugins/PluginLCA/test_lca.sh # [not win]
    - conda_recipe/plugins/PluginTeaser/test_teaser.sh # [not win]
    - bim2sim
    - test

about:
  home: https://github.com/BIM2SIM/bim2sim
  summary: "A python tool to create simulation models for different domains based on BIM IFC models."
  description: "A python tool to create simulation models for different domains based on BIM IFC models. For documentation please visit https://ebc.pages.rwth-aachen.de/EBC_all/github_ci/bim2sim/development/docs/overview.html"
  license: LICENSE
