from bim2sim.elements import bps_elements as bps_elements
from bim2sim.elements.base_elements import Material
from bim2sim.sim_settings import BuildingSimSettings, BooleanSetting, PathSetting



class VentilationSystemSimSettings(BuildingSimSettings):

    def __init__(self):
        super().__init__()
        self.relevant_elements = {*bps_elements.items,
                                      Material}

    export_graphs = BooleanSetting(
        value=True,
        description="Export the figures of the ventilation graphs")

    teaser_result_file = PathSetting(
        value=None,
        description='Path to the dymola mat file which was generated by '
                    'bim2sim plugin teaser',
        for_frontend=True,
        mandatory=True
    )
    serialized_elements_path = PathSetting(
        value=None,
        description='Path to the pickled/serialized elements file',
        for_frontend=True,
        mandatory=True
    )



