stages:
  - build
  - release


.base_docker_build: &base_docker_build
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      variables:
        HEALTHCHECK_TCP_PORT: "2376"

.base_build_template: &base_build_template
  <<: *base_docker_build
  script:
    - docker login -u $CI_DEPLOY_TOKEN_USERNAME -p $CI_DEPLOY_TOKEN_PASSWORD $CI_REGISTRY_LOGIN
    - echo ${CI_PROJECT_DIR}
    - docker build 
      --build-arg PYTHON_VERSION=${PYTHON_VERSION}
      --build-arg FROM_BUILD_TAG=${FROM_BUILD_TAG}
      -t $CI_REGISTRY/bim2sim:$TAG -f ${DOCKERFILE} .
    - docker push $CI_REGISTRY/bim2sim:$TAG

.build_template: &build_template
  stage: build
  <<: *base_build_template

.release_template: &release_template
  stage: release
  <<: *base_build_template

.build_template_dymola: &build_template_dymola
  <<: *base_docker_build
  stage: build
  before_script:
    # Before, login dymola docker reg
    - docker login -u $CI_DEPLOY_TOKEN_USERNAME_DYMOLA -p $CI_DEPLOY_TOKEN_PASSWORD_DYMOLA $CI_REGISTRY_LOGIN_DYMOLA

# Development branch base builds
build:py3.10-occ7.7.0:
  <<: *build_template
  variables:
    PYTHON_VERSION: "3.10"
    TAG: "py3.10-occ7.7.0"
    DOCKERFILE: ci/Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "development" || $CI_COMMIT_REF_NAME == "822_eplus_ci"'
      changes:
        - ci/*
        - pyproject.toml
        - .gitlab-ci.yml
        - bim2sim/plugins/**/*.Dockerfile

build:py3.11-occ7.7.0:
  <<: *build_template
  variables:
    PYTHON_VERSION: "3.11"
    TAG: "py3.11-occ7.7.0"
    DOCKERFILE: ci/Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "development" || $CI_COMMIT_REF_NAME == "822_eplus_ci"'
      changes:
        - ci/*
        - pyproject.toml
        - .gitlab-ci.yml
        - bim2sim/plugins/**/*.Dockerfile

# Development branch plugin builds
release:dev-PluginTEASER-py.310:
  <<: *release_template
  variables:
    FROM_BUILD_TAG: "py3.10-occ7.7.0"
    TAG: dev-PluginTEASER-py3.10
    DOCKERFILE: bim2sim/plugins/PluginTEASER/PluginTEASER.Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "development" || $CI_COMMIT_REF_NAME == "822_eplus_ci"'
      changes:
        - ci/*
        - bim2sim/plugins/PluginTEASER/PluginTEASER.Dockerfile
        - pyproject.toml
        - .gitlab-ci.yml

release:dev-PluginTEASER-py.311:
  <<: *release_template
  variables:
    FROM_BUILD_TAG: "py3.11-occ7.7.0"
    TAG: dev-PluginTEASER-py3.11
    DOCKERFILE: bim2sim/plugins/PluginTEASER/PluginTEASER.Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "development" || $CI_COMMIT_REF_NAME == "822_eplus_ci"'
      changes:
        - ci/*
        - bim2sim/plugins/PluginTEASER/PluginTEASER.Dockerfile
        - pyproject.toml
        - .gitlab-ci.yml

release:dev-PluginAixLib-py.310:
  <<: *release_template
  variables:
    FROM_BUILD_TAG: "py3.10-occ7.7.0"
    TAG: dev-PluginAixLib-py3.10
    DOCKERFILE: bim2sim/plugins/PluginAixLib/PluginAixLib.Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "development" || $CI_COMMIT_REF_NAME == "822_eplus_ci"'
      changes:
        - ci/*
        - bim2sim/plugins/PluginAixLib/PluginAixLib.Dockerfile
        - pyproject.toml
        - .gitlab-ci.yml

release:dev-PluginAixLib-py.311:
  <<: *release_template
  variables:
    FROM_BUILD_TAG: "py3.11-occ7.7.0"
    TAG: dev-PluginAixLib-py3.11
    DOCKERFILE: bim2sim/plugins/PluginAixLib/PluginAixLib.Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "development" || $CI_COMMIT_REF_NAME == "822_eplus_ci"'
      changes:
        - ci/*
        - bim2sim/plugins/PluginAixLib/PluginAixLib.Dockerfile
        - pyproject.toml
        - .gitlab-ci.yml

release:dev-PluginHKESim-py.310:
  <<: *release_template
  variables:
    FROM_BUILD_TAG: "py3.10-occ7.7.0"
    TAG: dev-PluginHKESim-py3.10
    DOCKERFILE: bim2sim/plugins/PluginHKESim/PluginHKESim.Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "development" || $CI_COMMIT_REF_NAME == "822_eplus_ci"'
      changes:
        - ci/*
        - bim2sim/plugins/PluginHKESim/PluginHKESim.Dockerfile
        - pyproject.toml
        - .gitlab-ci.yml

release:dev-PluginHKESim-py.311:
  <<: *release_template
  variables:
    FROM_BUILD_TAG: "py3.11-occ7.7.0"
    TAG: dev-PluginHKESim-py3.11
    DOCKERFILE: bim2sim/plugins/PluginHKESim/PluginHKESim.Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "development" || $CI_COMMIT_REF_NAME == "822_eplus_ci"'
      changes:
        - ci/*
        - bim2sim/plugins/PluginHKESim/PluginHKESim.Dockerfile
        - pyproject.toml
        - .gitlab-ci.yml

release:dev-PluginEnergyPlus-py.310:
  <<: *release_template
  variables:
    FROM_BUILD_TAG: "energyplus-py3.10"
    TAG: dev-PluginEnergyPlus-py3.10
    DOCKERFILE: bim2sim/plugins/PluginEnergyPlus/PluginEnergyPlus.Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "development" || $CI_COMMIT_REF_NAME == "822_eplus_ci"'
      changes:
        - ci/*
        - bim2sim/plugins/PluginEnergyPlus/PluginEnergyPlus.Dockerfile
        - pyproject.toml
        - .gitlab-ci.yml

release:dev-PluginEnergyPlus-py.311:
  <<: *release_template
  variables:
    FROM_BUILD_TAG: "energyplus9.4.0-py3.11"
    TAG: dev-PluginEnergyPlus-py3.11
    DOCKERFILE: bim2sim/plugins/PluginEnergyPlus/PluginEnergyPlus.Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "development" || $CI_COMMIT_REF_NAME == "822_eplus_ci"'
      changes:
        - ci/*
        - bim2sim/plugins/PluginEnergyPlus/PluginEnergyPlus.Dockerfile
        - pyproject.toml
        - .gitlab-ci.yml

release:dev-PluginComfort-py.310:
  <<: *release_template
  variables:
    FROM_BUILD_TAG: "energyplus-py3.10"
    TAG: dev-PluginComfort-py3.10
    DOCKERFILE: bim2sim/plugins/PluginComfort/PluginComfort.Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "development" || $CI_COMMIT_REF_NAME == "822_eplus_ci"'
      changes:
        - ci/*
        - bim2sim/plugins/PluginComfort/PluginComfort.Dockerfile
        - pyproject.toml
        - .gitlab-ci.yml

release:dev-PluginComfort-py.311:
  <<: *release_template
  variables:
    FROM_BUILD_TAG: "energyplus9.4.0-py3.11"
    TAG: dev-PluginComfort-py3.11
    DOCKERFILE: bim2sim/plugins/PluginComfort/PluginComfort.Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "development" || $CI_COMMIT_REF_NAME == "822_eplus_ci"'
      changes:
        - ci/*
        - bim2sim/plugins/PluginComfort/PluginComfort.Dockerfile
        - pyproject.toml
        - .gitlab-ci.yml

release:dev-PluginOpenFOAM-py.310:
  <<: *release_template
  variables:
    FROM_BUILD_TAG: "energyplus-py3.10"
    TAG: dev-PluginOpenFOAM-py3.10
    DOCKERFILE: bim2sim/plugins/PluginOpenFOAM/PluginOpenFOAM.Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "development" || $CI_COMMIT_REF_NAME == "822_eplus_ci"'
    - changes:
        - ci/*
        - bim2sim/plugins/PluginOpenFOAM/PluginOpenFOAM.Dockerfile
        - pyproject.toml
        - .gitlab-ci.yml

release:dev-PluginOpenFOAM-py.311:
  <<: *release_template
  variables:
    FROM_BUILD_TAG: "energyplus9.4.0-py3.11"
    TAG: dev-PluginOpenFOAM-py3.11
    DOCKERFILE: bim2sim/plugins/PluginOpenFOAM/PluginOpenFOAM.Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "development" || $CI_COMMIT_REF_NAME == "822_eplus_ci"'
    - changes:
        - ci/*
        - bim2sim/plugins/PluginOpenFOAM/PluginOpenFOAM.Dockerfile
        - pyproject.toml
        - .gitlab-ci.yml

# TODO PluginLCA currently has no dependencies, but might have in the future
release:dev-PluginLCA-py.310:
  <<: *release_template
  variables:
    FROM_BUILD_TAG: "py3.10-occ7.7.0"
    TAG: dev-PluginLCA-py3.10
    DOCKERFILE: bim2sim/plugins/PluginLCA/PluginLCA.Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "development" || $CI_COMMIT_REF_NAME == "822_eplus_ci"'
      changes:
        - ci/*
        - bim2sim/plugins/PluginLCA/PluginLCA.Dockerfile
        - pyproject.toml
        - .gitlab-ci.yml

# TODO PluginLCA currently has no dependencies, but might have in the future
release:dev-PluginLCA-py.311:
  <<: *release_template
  variables:
    FROM_BUILD_TAG: "py3.11-occ7.7.0"
    TAG: dev-PluginLCA-py3.11
    DOCKERFILE: bim2sim/plugins/PluginLCA/PluginLCA.Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "development" || $CI_COMMIT_REF_NAME == "822_eplus_ci"'
      changes:
        - ci/*
        - bim2sim/plugins/PluginLCA/PluginLCA.Dockerfile
        - pyproject.toml
        - .gitlab-ci.yml

# Build dymola images
build:dymola2022-py.310:
  <<: *build_template_dymola
  variables:
    PYTHON_VERSION: "3.10"
    FROM_BUILD_TAG: "Dymola_2022"
    TAG: dymola2022-py3.10
    DOCKERFILE: ci/Dymola.Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "development" || $CI_COMMIT_REF_NAME == "822_eplus_ci"'
      changes:
        - ci/*
        - pyproject.toml
        - .gitlab-ci.yml

build:dymola2022-py.311:
  <<: *build_template_dymola
  variables:
    PYTHON_VERSION: "3.11"
    FROM_BUILD_TAG: "Dymola_2022"
    TAG: dymola2022-py3.11
    DOCKERFILE: ci/Dymola.Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "development" || $CI_COMMIT_REF_NAME == "822_eplus_ci"'
      changes:
        - ci/*
        - pyproject.toml
        - .gitlab-ci.yml


# Main branch plugin releases
release:main-PluginTEASER-py.310:
  <<: *release_template
  variables:
    FROM_BUILD_TAG: "py3.10-occ7.7.0"
    TAG: main-PluginTEASER-py3.10
    DOCKERFILE: bim2sim/plugins/PluginTEASER/PluginTEASER.Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      changes:
        - ci/*
        - bim2sim/plugins/PluginTEASER/PluginTEASER.Dockerfile
        - pyproject.toml
        - .gitlab-ci.yml

release:main-PluginTEASER-py.311:
  <<: *release_template
  variables:
    FROM_BUILD_TAG: "py3.11-occ7.7.0"
    TAG: main-PluginTEASER-py3.11
    DOCKERFILE: bim2sim/plugins/PluginTEASER/PluginTEASER.Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      changes:
        - ci/*
        - bim2sim/plugins/PluginTEASER/PluginTEASER.Dockerfile
        - pyproject.toml
        - .gitlab-ci.yml

release:main-PluginAixLib-py.310:
  <<: *release_template
  variables:
    FROM_BUILD_TAG: "py3.10-occ7.7.0"
    TAG: main-PluginAixLib-py3.10
    DOCKERFILE: bim2sim/plugins/PluginAixLib/PluginAixLib.Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      changes:
        - ci/*
        - bim2sim/plugins/PluginAixLib/PluginAixLib.Dockerfile
        - pyproject.toml
        - .gitlab-ci.yml

release:main-PluginAixLib-py.311:
  <<: *release_template
  variables:
    FROM_BUILD_TAG: "py3.11-occ7.7.0"
    TAG: main-PluginAixLib-py3.11
    DOCKERFILE: bim2sim/plugins/PluginAixLib/PluginAixLib.Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      changes:
        - ci/*
        - bim2sim/plugins/PluginAixLib/PluginAixLib.Dockerfile
        - pyproject.toml
        - .gitlab-ci.yml

release:main-PluginHKESim-py.310:
  <<: *release_template
  variables:
    FROM_BUILD_TAG: "py3.10-occ7.7.0"
    TAG: main-PluginHKESim-py3.10
    DOCKERFILE: bim2sim/plugins/PluginHKESim/PluginHKESim.Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      changes:
        - ci/*
        - bim2sim/plugins/PluginHKESim/PluginHKESim.Dockerfile
        - pyproject.toml
        - .gitlab-ci.yml

release:main-PluginHKESim-py.311:
  <<: *release_template
  variables:
    FROM_BUILD_TAG: "py3.11-occ7.7.0"
    TAG: main-PluginHKESim-py3.11
    DOCKERFILE: bim2sim/plugins/PluginHKESim/PluginHKESim.Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      changes:
        - ci/*
        - bim2sim/plugins/PluginHKESim/PluginHKESim.Dockerfile
        - pyproject.toml
        - .gitlab-ci.yml

release:main-PluginEnergyPlus-py.310:
  <<: *release_template
  variables:
    FROM_BUILD_TAG: "energyplus-py3.10"
    TAG: main-PluginEnergyPlus-py3.10
    DOCKERFILE: bim2sim/plugins/PluginEnergyPlus/PluginEnergyPlus.Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      changes:
        - ci/*
        - bim2sim/plugins/PluginEnergyPlus/PluginEnergyPlus.Dockerfile
        - pyproject.toml
        - .gitlab-ci.yml

release:main-PluginEnergyPlus-py.311:
  <<: *release_template
  variables:
    FROM_BUILD_TAG: "energyplus9.4.0-py3.11"
    TAG: main-PluginEnergyPlus-py3.11
    DOCKERFILE: bim2sim/plugins/PluginEnergyPlus/PluginEnergyPlus.Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      changes:
        - ci/*
        - bim2sim/plugins/PluginEnergyPlus/PluginEnergyPlus.Dockerfile
        - pyproject.toml
        - .gitlab-ci.yml

release:main-PluginComfort-py.310:
  <<: *release_template
  variables:
    FROM_BUILD_TAG: "energyplus-py3.10"
    TAG: main-PluginComfort-py3.10
    DOCKERFILE: bim2sim/plugins/PluginComfort/PluginComfort.Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      changes:
        - ci/*
        - bim2sim/plugins/PluginComfort/PluginComfort.Dockerfile
        - pyproject.toml
        - .gitlab-ci.yml

release:main-PluginComfort-py.311:
  <<: *release_template
  variables:
    FROM_BUILD_TAG: "energyplus-py3.10"
    TAG: main-PluginComfort-py3.11
    DOCKERFILE: bim2sim/plugins/PluginComfort/PluginComfort.Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      changes:
        - ci/*
        - bim2sim/plugins/PluginComfort/PluginComfort.Dockerfile
        - pyproject.toml
        - .gitlab-ci.yml

release:main-PluginOpenFOAM-py.310:
  <<: *release_template
  variables:
    FROM_BUILD_TAG: "energyplus-py3.10"
    TAG: main-PluginOpenFOAM-py3.10
    DOCKERFILE: bim2sim/plugins/PluginOpenFOAM/PluginOpenFOAM.Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      changes:
        - ci/*
        - bim2sim/plugins/PluginOpenFOAM/PluginOpenFOAM.Dockerfile
        - pyproject.toml
        - .gitlab-ci.yml

release:main-PluginOpenFOAM-py.311:
  <<: *release_template
  variables:
    FROM_BUILD_TAG: "energyplus-py3.10"
    TAG: main-PluginOpenFOAM-py3.11
    DOCKERFILE: bim2sim/plugins/PluginOpenFOAM/PluginOpenFOAM.Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      changes:
        - ci/*
        - bim2sim/plugins/PluginOpenFOAM/PluginOpenFOAM.Dockerfile
        - pyproject.toml
        - .gitlab-ci.yml

release:main-PluginLCA-py.310:
  <<: *release_template
  variables:
    FROM_BUILD_TAG: "py3.10-occ7.7.0"
    TAG: main-PluginLCA-py3.10
    DOCKERFILE: bim2sim/plugins/PluginLCA/PluginLCA.Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      changes:
        - ci/*
        - bim2sim/plugins/PluginLCA/PluginLCA.Dockerfile
        - pyproject.toml
        - .gitlab-ci.yml

release:main-PluginLCA-py.311:
  <<: *release_template
  variables:
    FROM_BUILD_TAG: "py3.11-occ7.7.0"
    TAG: main-PluginLCA-py3.11
    DOCKERFILE: bim2sim/plugins/PluginLCA/PluginLCA.Dockerfile
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      changes:
        - ci/*
        - bim2sim/plugins/PluginLCA/PluginLCA.Dockerfile
        - pyproject.toml
        - .gitlab-ci.yml


# Build EnergyPlus images
build:energyplus-py.310:
  <<: *build_template
  variables:
    FROM_BUILD_TAG: "py3.10-occ7.7.0"
    TAG: energyplus-py3.10
    DOCKERFILE: ci/EnergyPlus.Dockerfile
  needs:
    - build:py3.10-occ7.7.0
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main" || $CI_COMMIT_REF_NAME == "development" || $CI_COMMIT_REF_NAME == "822_eplus_ci"'
      changes:
        - ci/*
        - EnergyPlus.Dockerfile
        - pyproject.toml
        - .gitlab-ci.yml

build:energyplus-py.311:
  <<: *build_template
  variables:
    FROM_BUILD_TAG: "py3.11-occ7.7.0"
    TAG: energyplus9.4.0-py3.11
    DOCKERFILE: ci/EnergyPlus.Dockerfile
  needs:
    - build:py3.11-occ7.7.0
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main" || $CI_COMMIT_REF_NAME == "development" || $CI_COMMIT_REF_NAME == "822_eplus_ci"'
      changes:
        - ci/*
        - EnergyPlus.Dockerfile
        - pyproject.toml
        - .gitlab-ci.yml
