{% set version = "0.1.0" %}

package:
  name: "bim2sim"
  version: {{ version }}

source:
  path: ../

build:
  preserve_egg_dir: True
  number: '0'
  entry_points:
    - bim2sim = bim2sim.__main__:commandline_interface
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python>=3.8.*,<3.10.*
    - pip 22.2.2
    - setuptools 65.5.0
  run:
    - python >=3.8.*,<3.10.*
    - docopt 0.6.2
    - numpy 1.21.5
    - pandas 1.4.4
    - matplotlib 3.5.2
    - networkx>=2.2
    - python-dateutil 2.8.2
    - mako 1.2.4
    - pint 0.20.1
    - certifi 2022.12.7
    - pythonocc-core 7.6.2
    - ifcopenshell
  run_constrained:
    - beautifulsoup4 >=4.9.3

test:
  imports:
    - bim2sim
    - bim2sim.plugins.PluginAixLib
    - bim2sim.plugins.PluginTEASER
    - bim2sim.plugins.PluginCFD
    - bim2sim.plugins.PluginEnergyPlus
    - bim2sim.plugins.PluginLCA
  requires:
    - python  >=3.8.*,<3.10.*
    - pint==0.20.1
    - pythonocc-core==7.6.2
    - ifcopenshell

about:
  home: https://github.com/BIM2SIM/bim2sim
  summary: "Create simulation models from IFC files"
  description: |
  Create simulation models from IFC files
  license: LICENSE
