{% set version = "0.1.0" %}

package:
  name: "bim2sim"
  version: {{ version }}

source:
  path: ../

build:
  preserve_egg_dir: True
  number: '0'
  entry_points:
    - bim2sim = bim2sim:main

requirements:
  host:
    - python 3.9.15
    - pip 22.2.2
    - setuptools 65.5.0
    - docopt 0.6.2
    - numpy 1.21.5
    - pandas 1.4.4
    - matplotlib 3.5.2
    - networkx>=2.2
    - python-dateutil 2.8.2
    - mako 1.2.4
    - pint 0.20.1
  run:
    - python >=3.8.*,<3.10.*
test:
  imports:
    - bim2sim
    - bim2sim.plugins.PluginAixLib
    - bim2sim.plugins.PluginTEASER
    - bim2sim.plugins.PluginCFD
    - bim2sim.plugins.PluginEnergyPlus
    - bim2sim.plugins.PluginLCA
  requires:
    - python
    - pythonocc-core==7.6.2
    - ifcopenshell

about:
  home: https://github.com/BIM2SIM/bim2sim
  summary: "Create simulation models from IFC files"
  license: LICENSE