{% set version = "0.2.3" %}

package:
  name: "bim2sim"
  version: {{ version }}

source:
  path: ../


build:
  preserve_egg_dir: True
  number: 0
  noarch: python
  entry_points:
    - bim2sim = bim2sim:main


requirements:
  host:
    - python
    - pip
    - setuptools
  RUN:
    - python

test:
  imports:
    - bim2sim
    - bim2sim.plugins.PluginAixLib
    - bim2sim.plugins.PluginTEASER
  requires:
    - python
    - pythonocc-core==7.6.2
    - ifcopenshell

about:
  home: https://github.com/BIM2SIM/bim2sim
  summary: "Create simulation models from IFC files"
  license: LICENSE