{% set version = "0.1.7" %}

package:
  name: "bim2sim"
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  script: python setup.py install
  noarch: python

requirements:
  host:
    - python
    - pip
    - setuptools
    - pythonocc-core==7.6.2


  RUN:
    - python
    - pythonocc-core==7.6.2

test:
  imports:
    - bim2sim
    - bim2sim.plugins.PluginAixLib
    - bim2sim.plugins.PluginTEASER
  requires:
    - python
    - pythonocc-core==7.6.2
    - ifcopenshell

about:
  home: https://github.com/BIM2SIM/bim2sim
  summary: "Create simulation models from IFC files"
  license: LICENSE