{% set version = "0.1.0" %}

package:
  name: "bim2sim"
  version: {{ version }}

source:
  path: ../


build:
  preserve_egg_dir: True
  number: 0
  entry_points:
    - bim2sim = bim2sim:main


requirements:
  host:
    - python
    - pip
    - setuptools
  RUN:
    - python
    - docopt
    - numpy
    - pandas
    - matplotlib
    - networkx>=2.2
    - python-dateutil
    - mako
    - deep_translator
    - pint

test:
  imports:
    - bim2sim
    - bim2sim.plugins.PluginAixLib
    - bim2sim.plugins.PluginTEASER
    - bim2sim.plugins.PluginCFD
    - bim2sim.plugins.PluginEnergyPlus
    - bim2sim.plugins.PluginLCA
  requires:
    - python
    - pythonocc-core==7.6.2
    - ifcopenshell

about:
  home: https://github.com/BIM2SIM/bim2sim
  summary: "Create simulation models from IFC files"
  license: LICENSE