name: bim2sim_single
channels:
  - conda-forge
  - defaults
  -
dependencies:
  - boost-cpp=1.72.0
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - fontconfig=2.13.1
  - freetype=2.10.1
  - icu=64.2
  - ifcopenshell=v0.6.0
  - libiconv=1.15
  - libpng=1.6.37
  - libxml2=2.9.10
  - occt=7.4.0
  - openssl=1.1.1f
  - pip=20.0.2
  - python=3.7.6
  - python_abi=3.7
  - setuptools=46.1.3
  - sqlite=3.31.1
  - tbb=2020.1
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wheel=0.34.2
  - wincertstore=0.2
  - zlib=1.2.11
  - pip:
    - atomicwrites==1.3.0
    - attrs==19.3.0
    - colorama==0.4.3
    - cycler==0.10.0
    - decorator==4.4.2
    - docopt==0.6.2
    - importlib-metadata==1.6.0
    - kiwisolver==1.1.0
    - mako==1.1.0
    - markupsafe==1.1.1
    - matplotlib==3.2.0
    - more-itertools==8.2.0
    - networkx==2.4
    - numpy==1.18.1
    - packaging==20.3
    - pandas==1.0.2
    - pint==0.12
    - pluggy==0.13.1
    - py==1.8.1
    - pyparsing==2.4.6
    - pytest==5.4.1
    - python-dateutil==2.8.1
    - pytz==2019.3
    - scipy==1.4.1
    - shapely==1.7.0
    - six==1.14.0
    - teaser==0.7.2
    - wcwidth==0.1.9
    - zipp==3.1.0


