name: bim2sim_base_env

channels:
  - dsdale24
  - inso
  - conda-forge
  - bim2sim
  - anaconda
dependencies:
  - bim2sim_base
  - pip:
    - -r requirements.txt
    - -r dependency_requirements.txt
