name: bim2sim_base_env

channels:
  - dsdale24
  - inso
  - conda-forge
  - bim2sim
  - anaconda
dependencies:
  - bim2sim_base
  - pip:
    - -r requirements.txt
    - https://github.com/tpaviot/pythonocc-utils/archive/refs/heads/master.zip
    - git+https://github.com/squidKid-deluxe/pyvis.git@fix-show
