{% set data = load_setup_py_data(setup_file='../../setup.py', from_recipe_dir=True) %}

package:
  name:  {{BIM2SIM_NAME}}
  version: {{data.get('version')}}{{BIM2SIM_FLAG}}

source:
  path: ../../

build:
  preserve_egg_dir: true
  number: '0'
  entry_points:
    - bim2sim = bim2sim.__main__:commandline_interface
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python>=3.8.*,<3.10.*
    - pip
    - setuptools 65.5.0
  run:
    - python >=3.8.*,<3.10.*
    - docopt 0.6.2.*
    - numpy 1.21.5.*
    - pandas 1.4.4.*
    - matplotlib 3.5.2.*
    - networkx>=2.2
    - python-dateutil 2.8.2.*
    - mako 1.2.4.*
    - pint 0.20.1.*
    - certifi 2022.12.7.*
    - pythonocc-core 7.5.1.*
    - ifcopenshell
    run_constrained:
    - beautifulsoup4 >=4.9.3

test:
  imports:
    - bim2sim
    - bim2sim.plugins.PluginAixLib
    - bim2sim.plugins.PluginCFD
    - bim2sim.plugins.PluginEnergyPlus
    - bim2sim.plugins.PluginHKESim
    - bim2sim.plugins.PluginLCA
    - bim2sim.plugins.PluginTEASER
  requires:
    - python  >=3.8.*,<3.10.*
    - pint==0.20.1
    - pythonocc-core==7.5.1
    - ifcopenshell
    # pip

  commands:
    - bim2sim -h
    - bim2sim --version
    - bash conda_recipe/basic_build/base_run_test.sh # [not win]
    - conda_recipe/basic_build/base_run_test.bat # [win]
    # pip check

  source_files:
    - conda_recipe/basic_build/base_run_test.sh # [not win]
    - conda_recipe/basic_build/base_run_test.bat # [ win]
    - bim2sim
    - test

about:
  home: https://github.com/BIM2SIM/bim2sim
  summary: "A python tool to create simulation models for different domains based on BIM IFC models."
  description: "A python tool to create simulation models for different domains based on BIM IFC models. For documentation please visit https://ebc.pages.rwth-aachen.de/EBC_all/github_ci/bim2sim/development/docs/overview.html"
  license: LICENSE
