{% set data = load_setup_py_data(setup_file='../../setup.py', from_recipe_dir=True) %}

package:
  name:  {{BIM2SIM_NAME}}
  version: {{data.get('version')}}{{BIM2SIM_FLAG}}

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: '0'
  entry_points:
    - bim2sim = bim2sim.__main__:commandline_interface
  script: python -m pip install --no-deps --ignore-installed .
  #missing_dso_whitelist:
    #- libstdcxx-ng # this is just an example

requirements:
  host:
    - python>=3.8.*,<3.10.*
    - pip 22.2.2
    - setuptools 65.5.0
    # numpy
    # cython
  run:
    - python >=3.8.*,<3.10.*
    - docopt
    - numpy
    - pandas
    - matplotlib
    - networkx>=2.2
    - python-dateutil
    - mako
    - pint
    - certifi
    - pythonocc-core<= 7.5.1.*
    - ifcopenshell
  run_constrained:
    - beautifulsoup4 >=4.9.3

test:
  requires:
    - python>=3.8.*,<3.10.*
    - pint
    - pythonocc-core==7.5.1
    - ifcopenshell
  source_files:
    - conda_recipe/basic_build/base_run_test.sh # [notwin]
    - conda_recipe/basic_build/base_run_test.bat # [win]
    - bim2sim
    - test
    - bim2sim/examples/e5_export_quantities_for_lca.py
  imports:
    - bim2sim
    - bim2sim.plugins.PluginAixLib
    - bim2sim.plugins.PluginCFD
    - bim2sim.plugins.PluginEnergyPlus
    - bim2sim.plugins.PluginHKESim
    - bim2sim.plugins.PluginLCA
    - bim2sim.plugins.PluginTEASER
  commands:
    - bim2sim -h
    - bim2sim --version
    - python bim2sim/examples/e5_export_quantities_for_lca.py
    - bash conda_recipe/basic_build/base_run_test.sh # [notwin]
    - conda_recipe/basic_build/base_run_test.bat # [win]



about:
  home: https://github.com/BIM2SIM/bim2sim
  summary: "A python tool to create simulation models for different domains based on BIM IFC models."
  description: "A python tool to create simulation models for different domains based on BIM IFC models. For documentation please visit https://ebc.pages.rwth-aachen.de/EBC_all/github_ci/bim2sim/development/docs/overview.html"
  license: LICENSE
