{% set data = load_setup_py_data(setup_file='../../setup.py', from_recipe_dir=True) %}

package:
  name:  {{BIM2SIM_NAME}}
  version: {{data.get('version')}}{{BIM2SIM_FLAG}}

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: '0'
  entry_points:
    - bim2sim = bim2sim.__main__:commandline_interface
  script: python -m pip install --no-deps --ignore-installed .
  missing_dso_whitelist:
    - libQt5Widgets.so.5
    - libQt5Gui.so.5
    - libtbb.so.2
    - libIfcParse.so.0.6
    - libIfcGeom.so.0.6
    - libpolyclipping.so.22
    - libgmp.so.10
    - libmpfr.so.6
    - libQt5Core.so.5
    - libTKSTEP.so.7
    - libTKIGES.so.7
    - libTKXSBase.so.7
    - libTKSTL.so.7
    - libTKVRML.so.7
    - libTKOpenGl.so.7
    - libTKOffset.so.7
    - libTKBO.so.7
    - libTKPrim.so.7
    - libTKV3d.so.7
    - libTKMesh.so.7
    - libTKShHealing.so.7
    - libTKTopAlgo.so.7
    - libTKBRep.so.7
    - libTKGeomBase.so.7
    - libTKG3d.so.7
    - libTKG2d.so.7
    - libTKService.so.7
    - libTKMath.so.7
    - libTKernel.so.7
    - libpthread.so.0
    - libstdc++.so.6
    - libm.so.6


requirements:
  host:
    - python>=3.8.*,<3.10.*
    - pip 22.2.2
    - setuptools 65.5.0
    - numpy
    - cython
  run:
    - python >=3.8.*,<3.10.*
    - pythonocc-core<= 7.5.1
    # pythonocc-core
    # ifcopenshell== v0.7.a6.*
    - ifcopenshell
    - occt<=7.5.1
    - docopt
    - numpy
    - pandas
    - matplotlib
    - networkx>=2.2
    # networkx
    - python-dateutil
    - mako
    - pint
    - certifi

  run_constrained:
    - beautifulsoup4 >=4.9.3

test:
  requires:
    - python>=3.8.*,<3.10.*
    - pint
    - pythonocc-core
    - ifcopenshell
  source_files:
    - conda_recipe/basic_build/base_run_test.sh # [not win]
    - conda_recipe/basic_build/base_run_test.bat # [win]
    - bim2sim
    - test
    - bim2sim/examples/e5_export_quantities_for_lca.py
  imports:
    - bim2sim
    - bim2sim.plugins.PluginAixLib
    - bim2sim.plugins.PluginCFD
    - bim2sim.plugins.PluginEnergyPlus
    - bim2sim.plugins.PluginHKESim
    - bim2sim.plugins.PluginLCA
    - bim2sim.plugins.PluginTEASER
  commands:
    - bim2sim -h
    - bim2sim --version
    - python bim2sim/examples/e5_export_quantities_for_lca.py
    - bash conda_recipe/basic_build/base_run_test.sh # [not win]
    - conda_recipe/basic_build/base_run_test.bat # [win]



about:
  home: https://github.com/BIM2SIM/bim2sim
  summary: "A python tool to create simulation models for different domains based on BIM IFC models."
  description: "A python tool to create simulation models for different domains based on BIM IFC models. For documentation please visit https://ebc.pages.rwth-aachen.de/EBC_all/github_ci/bim2sim/development/docs/overview.html"
  license: LICENSE
