{% set data = load_setup_py_data(setup_file='../../setup.py', from_recipe_dir=True) %}

package:
  name:  {{BIM2SIM_NAME}}
  version: {{data.get('version')}}{{BIM2SIM_FLAG}}

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: '0'
  entry_points:
    - bim2sim = bim2sim.__main__:commandline_interface
  script: python -m pip install --no-deps --ignore-installed .
  missing_dso_whitelist:
    - $RPATH/libQt5Widgets.so.5
    - $RPATH/libQt5Gui.so.5
    - $RPATH/libtbb.so.2
    - $RPATH/libIfcParse.so.0.6
    - $RPATH/libIfcGeom.so.0.6
    - $RPATH/libpolyclipping.so.22
    - $RPATH/libgmp.so.10
    - $RPATH/libmpfr.so.6
    - $RPATH/libQt5Core.so.5
    - $RPATH/libTKSTEP.so.7
    - $RPATH/libTKIGES.so.7
    - $RPATH/libTKXSBase.so.7
    - $RPATH/libTKSTL.so.7
    - $RPATH/libTKVRML.so.7
    - $RPATH/libTKOpenGl.so.7
    - $RPATH/libTKOffset.so.7
    - $RPATH/libTKBO.so.7
    - $RPATH/libTKPrim.so.7
    - $RPATH/libTKV3d.so.7
    - $RPATH/libTKMesh.so.7
    - $RPATH/libTKShHealing.so.7
    - $RPATH/libTKTopAlgo.so.7
    - $RPATH/libTKBRep.so.7
    - $RPATH/libTKGeomBase.so.7
    - $RPATH/libTKG3d.so.7
    - $RPATH/libTKG2d.so.7
    - $RPATH/libTKService.so.7
    - $RPATH/libTKMath.so.7
    - $RPATH/libTKernel.so.7
    - $RPATH/libpthread.so.0
    - $RPATH/libstdc++.so.6
    - $RPATH/libm.so.6


requirements:
  build:
    - git
    - cmake
    - gcc
  host:
    - python>=3.8.*,<3.10.*
    - pip 22.2.2
    - setuptools 65.5.0
    - numpy
    - cython
  run:
    - python >=3.8.*,<3.10.*
    - pythonocc-core<= 7.5.1
    # pythonocc-core
    # ifcopenshell== v0.7.a6.*
    - ifcopenshell
    - occt<=7.5.1
    - docopt
    - numpy
    - pandas
    - matplotlib
    - networkx>=2.2
    # networkx
    - python-dateutil
    - mako
    - pint
    - certifi

  run_constrained:
    - beautifulsoup4 >=4.9.3

test:
  requires:
    - python>=3.8.*,<3.10.*
    - pint
    - pythonocc-core
    - ifcopenshell
  source_files:
    - conda_recipe/basic_build/base_run_test.sh # [not win]
    - conda_recipe/basic_build/base_run_test.bat # [win]
    - bim2sim
    - test
    - bim2sim/examples/e5_export_quantities_for_lca.py
  imports:
    - bim2sim
    - bim2sim.plugins.PluginAixLib
    - bim2sim.plugins.PluginCFD
    - bim2sim.plugins.PluginEnergyPlus
    - bim2sim.plugins.PluginHKESim
    - bim2sim.plugins.PluginLCA
    - bim2sim.plugins.PluginTEASER
  commands:
    - bim2sim -h
    - bim2sim --version
    - python bim2sim/examples/e5_export_quantities_for_lca.py
    - bash conda_recipe/basic_build/base_run_test.sh # [not win]
    - conda_recipe/basic_build/base_run_test.bat # [win]



about:
  home: https://github.com/BIM2SIM/bim2sim
  summary: "A python tool to create simulation models for different domains based on BIM IFC models."
  description: "A python tool to create simulation models for different domains based on BIM IFC models. For documentation please visit https://ebc.pages.rwth-aachen.de/EBC_all/github_ci/bim2sim/development/docs/overview.html"
  license: LICENSE
